module

public import ADR11.FiveTaxa.Basic

/-!
# The balanced 5-taxon species tree `(((a,b):x,c):y,(d,e):z)`

Appendix B.1 (equation (11)), Table 1, the equivalence classes, the inequalities (4), their
exhaustiveness, and the extreme classes (Section 4.2.1). Throughout, `X = e^{-x}`, `Y = e^{-y}`,
`Z = e^{-z}` with `x, y, z` the lengths of the edges above `{a,b}`, `{a,b,c}` and `{d,e}`.
-/

@[expose] public section

namespace ADR11

open Finset Real

/-- **Equation (11)** (Appendix B.1): the unrooted gene tree distribution of the balanced species
tree `(((a,b):x,c):y,(d,e):z)`. -/
theorem equation11 (σ : SpeciesTree (Fin 5)) (hσ : σ.clusters = balanced5) :
    let X := exp (-σ.length {0, 1})
    let Y := exp (-σ.length {0, 1, 2})
    let Z := exp (-σ.length {3, 4})
    u σ 1 = 1 - 2 / 3 * X - 2 / 3 * Y * Z + 1 / 3 * X * Y * Z + 1 / 15 * X * Y ^ 3 * Z ∧
    u σ 2 = 1 / 3 * Y * Z - 1 / 6 * X * Y * Z - 1 / 10 * X * Y ^ 3 * Z ∧ u σ 3 = u σ 2 ∧
    u σ 4 = 1 / 3 * X - 1 / 3 * X * Y * Z + 1 / 15 * X * Y ^ 3 * Z ∧ u σ 13 = u σ 4 ∧
    u σ 5 = 1 / 6 * X * Y * Z - 1 / 10 * X * Y ^ 3 * Z ∧ u σ 6 = u σ 5 ∧ u σ 9 = u σ 5 ∧
      u σ 12 = u σ 5 ∧
    u σ 7 = 1 / 15 * X * Y ^ 3 * Z ∧ u σ 8 = u σ 7 ∧ u σ 10 = u σ 7 ∧ u σ 11 = u σ 7 ∧
      u σ 14 = u σ 7 ∧ u σ 15 = u σ 7 := by
  sorry

/-- The basis of homogeneous linear invariants listed in Table 1, in the order of the table. -/
def table1Basis : Fin 10 → Fin 15 → ℝ :=
  ![ue 14 - ue 15, ue 11 - ue 15, ue 10 - ue 15, ue 9 - ue 12, ue 8 - ue 15, ue 7 - ue 15,
    ue 6 - ue 12, ue 5 - ue 12, ue 4 - ue 13, ue 2 - ue 3]

/-- **Table 1.** The invariants listed form a basis of the homogeneous linear invariants of the
unrooted gene tree distributions of the species tree `(((a,b),c),(d,e))`. -/
theorem table1 :
    LinearIndependent ℝ table1Basis ∧
      Submodule.span ℝ (Set.range table1Basis) = linearInvariants balanced5 := by
  sorry

/-- The class of `T_i` in the partition of Section 4.2.1, named by its smallest index:
`{T₁}, {T₂,T₃}, {T₄,T₁₃}, {T₅,T₆,T₉,T₁₂}, {T₇,T₈,T₁₀,T₁₁,T₁₄,T₁₅}`. -/
def balancedClass : ℕ → ℕ
  | 3 => 2 | 13 => 4 | 6 => 5 | 9 => 5 | 12 => 5
  | 8 => 7 | 10 => 7 | 11 => 7 | 14 => 7 | 15 => 7 | i => i

/-- The equivalence classes of unrooted gene trees according to their probabilities: `T_i` and
`T_j` have the same probability for all branch lengths exactly when they lie in the same class. -/
theorem balanced_classes (i j : ℕ) (hi : i ∈ Icc 1 15) (hj : j ∈ Icc 1 15) :
    (∀ σ : SpeciesTree (Fin 5), σ.clusters = balanced5 → u σ i = u σ j) ↔
      balancedClass i = balancedClass j := by
  sorry

/-- **Inequalities (4)**: for all branch lengths, `u₁ > u₂ > u₅`, `u₁ > u₄ > u₅` and `u₅ > u₇`. -/
theorem equation4 (σ : SpeciesTree (Fin 5)) (hσ : σ.clusters = balanced5) :
    u σ 1 > u σ 2 ∧ u σ 1 > u σ 4 ∧ u σ 2 > u σ 5 ∧ u σ 4 > u σ 5 ∧ u σ 5 > u σ 7 := by
  sorry

/-- The strict order between classes generated by the inequalities (4) (pairs of class names). -/
def balancedOrder : Finset (ℕ × ℕ) :=
  {(1, 2), (1, 4), (1, 5), (1, 7), (2, 5), (2, 7), (4, 5), (4, 7), (5, 7)}

/-- Section 4.2.1: there are no inequalities `u_i > u_j` holding for all branch lengths other than
those implied by (4) and the equalities of Table 1. -/
theorem equation4_exhaustive (i j : ℕ) (hi : i ∈ Icc 1 15) (hj : j ∈ Icc 1 15) :
    (∀ σ : SpeciesTree (Fin 5), σ.clusters = balanced5 → u σ i > u σ j) ↔
      (balancedClass i, balancedClass j) ∈ balancedOrder := by
  sorry

open scoped Classical in
/-- Section 4.2.1: the 6-element class always has the strictly smallest probability, the
4-element class the next smallest, and the class of the largest probability is the singleton
`{T₁}`. -/
theorem balanced_extremeClasses (σ : SpeciesTree (Fin 5)) (hσ : σ.clusters = balanced5) :
    {i ∈ Icc 1 15 | ∀ j ∈ Icc 1 15, u σ i ≤ u σ j} = {7, 8, 10, 11, 14, 15} ∧
    {i ∈ Icc 1 15 | u σ 7 < u σ i ∧ ∀ j ∈ Icc 1 15, u σ 7 < u σ j → u σ i ≤ u σ j} =
      {5, 6, 9, 12} ∧
    {i ∈ Icc 1 15 | ∀ j ∈ Icc 1 15, u σ j ≤ u σ i} = {1} := by
  sorry

/-- Section 4.2.1: the two classes of size 2 can degenerate to a single class of size 4. -/
theorem balanced_degenerate :
    ∃ σ : SpeciesTree (Fin 5), σ.clusters = balanced5 ∧ u σ 2 = u σ 4 := by
  sorry

end ADR11
