module

public import ADR11.FiveTaxa.Basic

/-!
# The rooted caterpillar 5-taxon species tree `((((a,b):x,c):y,d):z,e)`

Appendix B.2 (equation (12)), Table 2, the marginalization invariant, the equivalence classes,
the inequalities (5) and their exhaustiveness (Section 4.2.2). Throughout, `X = e^{-x}`,
`Y = e^{-y}`, `Z = e^{-z}` with `x, y, z` the lengths of the edges above `{a,b}`, `{a,b,c}` and
`{a,b,c,d}`.
-/

@[expose] public section

namespace ADR11

open Finset Real

/-- **Equation (12)** (Appendix B.2): the unrooted gene tree distribution of the rooted caterpillar
species tree `((((a,b):x,c):y,d):z,e)`. -/
theorem equation12 (σ : SpeciesTree (Fin 5)) (hσ : σ.clusters = caterpillar5) :
    let X := exp (-σ.length {0, 1})
    let Y := exp (-σ.length {0, 1, 2})
    let Z := exp (-σ.length {0, 1, 2, 3})
    u σ 1 = 1 - 2 / 3 * X - 2 / 3 * Y + 1 / 3 * X * Y + 1 / 18 * X * Y ^ 3 +
        1 / 90 * X * Y ^ 3 * Z ^ 6 ∧
    u σ 2 = 1 / 3 * Y - 1 / 6 * X * Y - 1 / 9 * X * Y ^ 3 + 1 / 90 * X * Y ^ 3 * Z ^ 6 ∧
    u σ 3 = 1 / 3 * Y - 1 / 6 * X * Y - 1 / 18 * X * Y ^ 3 - 2 / 45 * X * Y ^ 3 * Z ^ 6 ∧
    u σ 4 = 1 / 3 * X - 1 / 3 * X * Y + 1 / 18 * X * Y ^ 3 + 1 / 90 * X * Y ^ 3 * Z ^ 6 ∧
      u σ 13 = u σ 4 ∧
    u σ 5 = 1 / 6 * X * Y - 1 / 9 * X * Y ^ 3 + 1 / 90 * X * Y ^ 3 * Z ^ 6 ∧ u σ 12 = u σ 5 ∧
    u σ 6 = 1 / 6 * X * Y - 1 / 18 * X * Y ^ 3 - 2 / 45 * X * Y ^ 3 * Z ^ 6 ∧ u σ 9 = u σ 6 ∧
    u σ 7 = 1 / 18 * X * Y ^ 3 + 1 / 90 * X * Y ^ 3 * Z ^ 6 ∧ u σ 8 = u σ 7 ∧
      u σ 10 = u σ 7 ∧ u σ 11 = u σ 7 ∧ u σ 14 = u σ 7 ∧ u σ 15 = u σ 7 := by
  sorry

/-- The basis of homogeneous linear invariants listed in Table 2, in the order of the table. -/
def table2Basis : Fin 9 → Fin 15 → ℝ :=
  ![ue 14 - ue 15, ue 11 - ue 15, ue 10 - ue 15, ue 8 - ue 15, ue 7 - ue 15, ue 6 - ue 9,
    ue 5 - ue 12, ue 4 - ue 13, ue 2 - ue 3 + ue 9 - ue 12]

/-- **Table 2.** The invariants listed form a basis of the homogeneous linear invariants of the
unrooted gene tree distributions of the species tree `((((a,b),c),d),e)`. -/
theorem table2 :
    LinearIndependent ℝ table2Basis ∧
      Submodule.span ℝ (Set.range table2Basis) = linearInvariants caterpillar5 := by
  sorry

/-- The marginalization argument of Section 4.2.2: on the taxa `{b,c,d,e}` the two quartets that
disagree with the species tree are equiprobable, which gives
`u₂ + u₆ + u₇ + u₁₁ + u₁₄ = u₃ + u₅ + u₈ + u₁₀ + u₁₅`, and then the last invariant of Table 2. -/
theorem caterpillar_marginalization (σ : SpeciesTree (Fin 5)) (hσ : σ.clusters = caterpillar5) :
    u σ 2 + u σ 6 + u σ 7 + u σ 11 + u σ 14 = u σ 3 + u σ 5 + u σ 8 + u σ 10 + u σ 15 ∧
      u σ 2 - u σ 3 + u σ 9 - u σ 12 = 0 := by
  sorry

/-- The class of `T_i` in the partition of Section 4.2.2, named by its smallest index:
`{T₁}, {T₂}, {T₃}, {T₄,T₁₃}, {T₅,T₁₂}, {T₆,T₉}, {T₇,T₈,T₁₀,T₁₁,T₁₄,T₁₅}`. -/
def caterpillarClass : ℕ → ℕ
  | 13 => 4 | 12 => 5 | 9 => 6
  | 8 => 7 | 10 => 7 | 11 => 7 | 14 => 7 | 15 => 7 | i => i

/-- The equivalence classes of unrooted gene trees according to their probabilities. -/
theorem caterpillar_classes (i j : ℕ) (hi : i ∈ Icc 1 15) (hj : j ∈ Icc 1 15) :
    (∀ σ : SpeciesTree (Fin 5), σ.clusters = caterpillar5 → u σ i = u σ j) ↔
      caterpillarClass i = caterpillarClass j := by
  sorry

/-- **Inequalities (5)**: for all branch lengths, `u₁ > u₂ > u₅`, `u₁ > u₄ > u₅`, `u₃ > u₂`,
`u₃ > u₆ > u₅` and `u₅ > u₇`. -/
theorem equation5 (σ : SpeciesTree (Fin 5)) (hσ : σ.clusters = caterpillar5) :
    u σ 1 > u σ 2 ∧ u σ 1 > u σ 4 ∧ u σ 2 > u σ 5 ∧ u σ 4 > u σ 5 ∧ u σ 5 > u σ 7 ∧
      u σ 3 > u σ 2 ∧ u σ 3 > u σ 6 ∧ u σ 6 > u σ 5 := by
  sorry

/-- The strict order between classes generated by the inequalities (5). -/
def caterpillarOrder : Finset (ℕ × ℕ) :=
  {(1, 2), (1, 4), (1, 5), (1, 7), (3, 2), (3, 6), (3, 5), (3, 7), (2, 5), (2, 7), (4, 5), (4, 7),
    (6, 5), (6, 7), (5, 7)}

/-- Section 4.2.2: there are no inequalities `u_i > u_j` holding for all branch lengths other than
those implied by (5) and the equalities of Table 2. -/
theorem equation5_exhaustive (i j : ℕ) (hi : i ∈ Icc 1 15) (hj : j ∈ Icc 1 15) :
    (∀ σ : SpeciesTree (Fin 5), σ.clusters = caterpillar5 → u σ i > u σ j) ↔
      (caterpillarClass i, caterpillarClass j) ∈ caterpillarOrder := by
  sorry

open scoped Classical in
/-- From the inequalities (5): the 6-element class always has the strictly smallest probability
and the class `{T₅, T₁₂}` the next smallest (used in the proof of Proposition 7). -/
theorem caterpillar_extremeClasses (σ : SpeciesTree (Fin 5)) (hσ : σ.clusters = caterpillar5) :
    {i ∈ Icc 1 15 | ∀ j ∈ Icc 1 15, u σ i ≤ u σ j} = {7, 8, 10, 11, 14, 15} ∧
    {i ∈ Icc 1 15 | u σ 7 < u σ i ∧ ∀ j ∈ Icc 1 15, u σ 7 < u σ j → u σ i ≤ u σ j} =
      {5, 12} := by
  sorry

end ADR11
