module

public import ADR11.FiveTaxa.Basic

/-!
# The pseudocaterpillar 5-taxon species tree `(((a,b):x,(d,e):y):z,c)`

Appendix B.3 (equation (13)), Table 3, the equivalence classes, the inequalities (6) and their
exhaustiveness (Section 4.2.3). Throughout, `X = e^{-x}`, `Y = e^{-y}`, `Z = e^{-z}` with
`x, y, z` the lengths of the edges above `{a,b}`, `{d,e}` and `{a,b,d,e}`.
-/

@[expose] public section

namespace ADR11

open Finset Real

/-- **Equation (13)** (Appendix B.3): the unrooted gene tree distribution of the pseudocaterpillar
species tree `(((a,b):x,(d,e):y):z,c)`. -/
theorem equation13 (σ : SpeciesTree (Fin 5)) (hσ : σ.clusters = pseudocaterpillar5) :
    let X := exp (-σ.length {0, 1})
    let Y := exp (-σ.length {3, 4})
    let Z := exp (-σ.length {0, 1, 3, 4})
    u σ 1 = 1 - 2 / 3 * X - 2 / 3 * Y + 4 / 9 * X * Y - 2 / 45 * X * Y * Z ^ 6 ∧
    u σ 2 = 1 / 3 * Y - 5 / 18 * X * Y + 1 / 90 * X * Y * Z ^ 6 ∧ u σ 3 = u σ 2 ∧
    u σ 4 = 1 / 3 * X - 5 / 18 * X * Y + 1 / 90 * X * Y * Z ^ 6 ∧ u σ 13 = u σ 4 ∧
    u σ 5 = 1 / 18 * X * Y + 1 / 90 * X * Y * Z ^ 6 ∧ u σ 6 = u σ 5 ∧ u σ 7 = u σ 5 ∧
      u σ 9 = u σ 5 ∧ u σ 10 = u σ 5 ∧ u σ 12 = u σ 5 ∧ u σ 14 = u σ 5 ∧ u σ 15 = u σ 5 ∧
    u σ 8 = 1 / 9 * X * Y - 2 / 45 * X * Y * Z ^ 6 ∧ u σ 11 = u σ 8 := by
  sorry

/-- The basis of homogeneous linear invariants listed in Table 3, in the order of the table. -/
def table3Basis : Fin 10 → Fin 15 → ℝ :=
  ![ue 14 - ue 15, ue 12 - ue 15, ue 10 - ue 15, ue 9 - ue 15, ue 8 - ue 11, ue 7 - ue 15,
    ue 6 - ue 15, ue 5 - ue 15, ue 4 - ue 13, ue 2 - ue 3]

/-- **Table 3.** The invariants listed form a basis of the homogeneous linear invariants of the
unrooted gene tree distributions of the species tree `(((a,b),(d,e)),c)`. -/
theorem table3 :
    LinearIndependent ℝ table3Basis ∧
      Submodule.span ℝ (Set.range table3Basis) = linearInvariants pseudocaterpillar5 := by
  sorry

/-- The class of `T_i` in the partition of Section 4.2.3, named by its smallest index:
`{T₁}, {T₂,T₃}, {T₄,T₁₃}, {T₈,T₁₁}, {T₅,T₆,T₇,T₉,T₁₀,T₁₂,T₁₄,T₁₅}`. -/
def pseudocaterpillarClass : ℕ → ℕ
  | 3 => 2 | 13 => 4 | 11 => 8
  | 6 => 5 | 7 => 5 | 9 => 5 | 10 => 5 | 12 => 5 | 14 => 5 | 15 => 5 | i => i

/-- The equivalence classes of unrooted gene trees according to their probabilities. -/
theorem pseudocaterpillar_classes (i j : ℕ) (hi : i ∈ Icc 1 15) (hj : j ∈ Icc 1 15) :
    (∀ σ : SpeciesTree (Fin 5), σ.clusters = pseudocaterpillar5 → u σ i = u σ j) ↔
      pseudocaterpillarClass i = pseudocaterpillarClass j := by
  sorry

/-- **Inequalities (6)**: for all branch lengths, `u₁ > u₂ > u₅`, `u₁ > u₄ > u₅` and
`u₁ > u₈ > u₅`. -/
theorem equation6 (σ : SpeciesTree (Fin 5)) (hσ : σ.clusters = pseudocaterpillar5) :
    u σ 1 > u σ 2 ∧ u σ 1 > u σ 4 ∧ u σ 1 > u σ 8 ∧ u σ 2 > u σ 5 ∧ u σ 4 > u σ 5 ∧
      u σ 8 > u σ 5 := by
  sorry

/-- The strict order between classes generated by the inequalities (6). -/
def pseudocaterpillarOrder : Finset (ℕ × ℕ) :=
  {(1, 2), (1, 4), (1, 8), (1, 5), (2, 5), (4, 5), (8, 5)}

/-- Section 4.2.3: there are no inequalities `u_i > u_j` holding for all branch lengths other than
those implied by (6) and the equalities of Table 3. -/
theorem equation6_exhaustive (i j : ℕ) (hi : i ∈ Icc 1 15) (hj : j ∈ Icc 1 15) :
    (∀ σ : SpeciesTree (Fin 5), σ.clusters = pseudocaterpillar5 → u σ i > u σ j) ↔
      (pseudocaterpillarClass i, pseudocaterpillarClass j) ∈ pseudocaterpillarOrder := by
  sorry

open scoped Classical in
/-- Section 4.2.3: the 8-element class always has the strictly smallest probability. -/
theorem pseudocaterpillar_minClass (σ : SpeciesTree (Fin 5))
    (hσ : σ.clusters = pseudocaterpillar5) :
    {i ∈ Icc 1 15 | ∀ j ∈ Icc 1 15, u σ i ≤ u σ j} = {5, 6, 7, 9, 10, 12, 14, 15} := by
  sorry

end ADR11
