module

public import ADR11.SmallTrees

/-!
# Appendix A: the rooted and unrooted 5-taxon gene trees (Tables 4 and 5)

This file is generated by `scripts/gen_appendixA.py` from the paper's TeX source; do not edit it
by hand.

* `R5 j` (`1 ≤ j ≤ 105`): the rooted gene tree `R_j` of Table 4, as `hierarchyOf` its nontrivial
  clusters (taxa `A, …, E` are `0, …, 4`).
* `table4`: the `R_j` are distinct, each is a rooted binary tree, and every rooted binary tree on
  five taxa is one of them.
* `table5`: each unrooted gene tree probability `u_i` is the sum of the seven rooted gene tree
  probabilities `r_j = ℙ(R_j)` listed in Table 5.
-/

@[expose] public section

namespace ADR11

open Finset

/-- The rooted 5-taxon gene trees `R₁, …, R₁₀₅` of Table 4. -/
def R5 : ℕ → Finset (Finset (Fin 5))
  | 1 => hierarchyOf {{0, 1}, {0, 1, 2}, {0, 1, 2, 3}}  -- ((((A,B),C),D),E)
  | 2 => hierarchyOf {{0, 1}, {0, 1, 2}, {0, 1, 2, 4}}  -- ((((A,B),C),E),D)
  | 3 => hierarchyOf {{0, 1}, {0, 1, 3}, {0, 1, 2, 3}}  -- ((((A,B),D),C),E)
  | 4 => hierarchyOf {{0, 1}, {0, 1, 3}, {0, 1, 3, 4}}  -- ((((A,B),D),E),C)
  | 5 => hierarchyOf {{0, 1}, {0, 1, 4}, {0, 1, 2, 4}}  -- ((((A,B),E),C),D)
  | 6 => hierarchyOf {{0, 1}, {0, 1, 4}, {0, 1, 3, 4}}  -- ((((A,B),E),D),C)
  | 7 => hierarchyOf {{0, 2}, {0, 1, 2}, {0, 1, 2, 3}}  -- ((((A,C),B),D),E)
  | 8 => hierarchyOf {{0, 2}, {0, 1, 2}, {0, 1, 2, 4}}  -- ((((A,C),B),E),D)
  | 9 => hierarchyOf {{0, 2}, {0, 2, 3}, {0, 1, 2, 3}}  -- ((((A,C),D),B),E)
  | 10 => hierarchyOf {{0, 2}, {0, 2, 3}, {0, 2, 3, 4}}  -- ((((A,C),D),E),B)
  | 11 => hierarchyOf {{0, 2}, {0, 2, 4}, {0, 1, 2, 4}}  -- ((((A,C),E),B),D)
  | 12 => hierarchyOf {{0, 2}, {0, 2, 4}, {0, 2, 3, 4}}  -- ((((A,C),E),D),B)
  | 13 => hierarchyOf {{0, 3}, {0, 1, 3}, {0, 1, 2, 3}}  -- ((((A,D),B),C),E)
  | 14 => hierarchyOf {{0, 3}, {0, 1, 3}, {0, 1, 3, 4}}  -- ((((A,D),B),E),C)
  | 15 => hierarchyOf {{0, 3}, {0, 2, 3}, {0, 1, 2, 3}}  -- ((((A,D),C),B),E)
  | 16 => hierarchyOf {{0, 3}, {0, 2, 3}, {0, 2, 3, 4}}  -- ((((A,D),C),E),B)
  | 17 => hierarchyOf {{0, 3}, {0, 3, 4}, {0, 1, 3, 4}}  -- ((((A,D),E),B),C)
  | 18 => hierarchyOf {{0, 3}, {0, 3, 4}, {0, 2, 3, 4}}  -- ((((A,D),E),C),B)
  | 19 => hierarchyOf {{0, 4}, {0, 1, 4}, {0, 1, 2, 4}}  -- ((((A,E),B),C),D)
  | 20 => hierarchyOf {{0, 4}, {0, 1, 4}, {0, 1, 3, 4}}  -- ((((A,E),B),D),C)
  | 21 => hierarchyOf {{0, 4}, {0, 2, 4}, {0, 1, 2, 4}}  -- ((((A,E),C),B),D)
  | 22 => hierarchyOf {{0, 4}, {0, 2, 4}, {0, 2, 3, 4}}  -- ((((A,E),C),D),B)
  | 23 => hierarchyOf {{0, 4}, {0, 3, 4}, {0, 1, 3, 4}}  -- ((((A,E),D),B),C)
  | 24 => hierarchyOf {{0, 4}, {0, 3, 4}, {0, 2, 3, 4}}  -- ((((A,E),D),C),B)
  | 25 => hierarchyOf {{1, 2}, {0, 1, 2}, {0, 1, 2, 3}}  -- ((((B,C),A),D),E)
  | 26 => hierarchyOf {{1, 2}, {0, 1, 2}, {0, 1, 2, 4}}  -- ((((B,C),A),E),D)
  | 27 => hierarchyOf {{1, 2}, {1, 2, 3}, {0, 1, 2, 3}}  -- ((((B,C),D),A),E)
  | 28 => hierarchyOf {{1, 2}, {1, 2, 3}, {1, 2, 3, 4}}  -- ((((B,C),D),E),A)
  | 29 => hierarchyOf {{1, 2}, {1, 2, 4}, {0, 1, 2, 4}}  -- ((((B,C),E),A),D)
  | 30 => hierarchyOf {{1, 2}, {1, 2, 4}, {1, 2, 3, 4}}  -- ((((B,C),E),D),A)
  | 31 => hierarchyOf {{1, 3}, {0, 1, 3}, {0, 1, 2, 3}}  -- ((((B,D),A),C),E)
  | 32 => hierarchyOf {{1, 3}, {0, 1, 3}, {0, 1, 3, 4}}  -- ((((B,D),A),E),C)
  | 33 => hierarchyOf {{1, 3}, {1, 2, 3}, {0, 1, 2, 3}}  -- ((((B,D),C),A),E)
  | 34 => hierarchyOf {{1, 3}, {1, 2, 3}, {1, 2, 3, 4}}  -- ((((B,D),C),E),A)
  | 35 => hierarchyOf {{1, 3}, {1, 3, 4}, {0, 1, 3, 4}}  -- ((((B,D),E),A),C)
  | 36 => hierarchyOf {{1, 3}, {1, 3, 4}, {1, 2, 3, 4}}  -- ((((B,D),E),C),A)
  | 37 => hierarchyOf {{1, 4}, {0, 1, 4}, {0, 1, 2, 4}}  -- ((((B,E),A),C),D)
  | 38 => hierarchyOf {{1, 4}, {0, 1, 4}, {0, 1, 3, 4}}  -- ((((B,E),A),D),C)
  | 39 => hierarchyOf {{1, 4}, {1, 2, 4}, {0, 1, 2, 4}}  -- ((((B,E),C),A),D)
  | 40 => hierarchyOf {{1, 4}, {1, 2, 4}, {1, 2, 3, 4}}  -- ((((B,E),C),D),A)
  | 41 => hierarchyOf {{1, 4}, {1, 3, 4}, {0, 1, 3, 4}}  -- ((((B,E),D),A),C)
  | 42 => hierarchyOf {{1, 4}, {1, 3, 4}, {1, 2, 3, 4}}  -- ((((B,E),D),C),A)
  | 43 => hierarchyOf {{2, 3}, {0, 2, 3}, {0, 1, 2, 3}}  -- ((((C,D),A),B),E)
  | 44 => hierarchyOf {{2, 3}, {0, 2, 3}, {0, 2, 3, 4}}  -- ((((C,D),A),E),B)
  | 45 => hierarchyOf {{2, 3}, {1, 2, 3}, {0, 1, 2, 3}}  -- ((((C,D),B),A),E)
  | 46 => hierarchyOf {{2, 3}, {1, 2, 3}, {1, 2, 3, 4}}  -- ((((C,D),B),E),A)
  | 47 => hierarchyOf {{2, 3}, {2, 3, 4}, {0, 2, 3, 4}}  -- ((((C,D),E),A),B)
  | 48 => hierarchyOf {{2, 3}, {2, 3, 4}, {1, 2, 3, 4}}  -- ((((C,D),E),B),A)
  | 49 => hierarchyOf {{2, 4}, {0, 2, 4}, {0, 1, 2, 4}}  -- ((((C,E),A),B),D)
  | 50 => hierarchyOf {{2, 4}, {0, 2, 4}, {0, 2, 3, 4}}  -- ((((C,E),A),D),B)
  | 51 => hierarchyOf {{2, 4}, {1, 2, 4}, {0, 1, 2, 4}}  -- ((((C,E),B),A),D)
  | 52 => hierarchyOf {{2, 4}, {1, 2, 4}, {1, 2, 3, 4}}  -- ((((C,E),B),D),A)
  | 53 => hierarchyOf {{2, 4}, {2, 3, 4}, {0, 2, 3, 4}}  -- ((((C,E),D),A),B)
  | 54 => hierarchyOf {{2, 4}, {2, 3, 4}, {1, 2, 3, 4}}  -- ((((C,E),D),B),A)
  | 55 => hierarchyOf {{3, 4}, {0, 3, 4}, {0, 1, 3, 4}}  -- ((((D,E),A),B),C)
  | 56 => hierarchyOf {{3, 4}, {0, 3, 4}, {0, 2, 3, 4}}  -- ((((D,E),A),C),B)
  | 57 => hierarchyOf {{3, 4}, {1, 3, 4}, {0, 1, 3, 4}}  -- ((((D,E),B),A),C)
  | 58 => hierarchyOf {{3, 4}, {1, 3, 4}, {1, 2, 3, 4}}  -- ((((D,E),B),C),A)
  | 59 => hierarchyOf {{3, 4}, {2, 3, 4}, {0, 2, 3, 4}}  -- ((((D,E),C),A),B)
  | 60 => hierarchyOf {{3, 4}, {2, 3, 4}, {1, 2, 3, 4}}  -- ((((D,E),C),B),A)
  | 61 => hierarchyOf {{0, 1}, {2, 3}, {0, 1, 2, 3}}  -- (((A,B),(C,D)),E)
  | 62 => hierarchyOf {{0, 2}, {1, 3}, {0, 1, 2, 3}}  -- (((A,C),(B,D)),E)
  | 63 => hierarchyOf {{0, 3}, {1, 2}, {0, 1, 2, 3}}  -- (((A,D),(B,C)),E)
  | 64 => hierarchyOf {{0, 1}, {2, 4}, {0, 1, 2, 4}}  -- (((A,B),(C,E)),D)
  | 65 => hierarchyOf {{0, 2}, {1, 4}, {0, 1, 2, 4}}  -- (((A,C),(B,E)),D)
  | 66 => hierarchyOf {{0, 4}, {1, 2}, {0, 1, 2, 4}}  -- (((A,E),(B,C)),D)
  | 67 => hierarchyOf {{0, 1}, {3, 4}, {0, 1, 3, 4}}  -- (((A,B),(D,E)),C)
  | 68 => hierarchyOf {{0, 3}, {1, 4}, {0, 1, 3, 4}}  -- (((A,D),(B,E)),C)
  | 69 => hierarchyOf {{0, 4}, {1, 3}, {0, 1, 3, 4}}  -- (((A,E),(B,D)),C)
  | 70 => hierarchyOf {{0, 2}, {3, 4}, {0, 2, 3, 4}}  -- (((A,C),(D,E)),B)
  | 71 => hierarchyOf {{0, 3}, {2, 4}, {0, 2, 3, 4}}  -- (((A,D),(C,E)),B)
  | 72 => hierarchyOf {{0, 4}, {2, 3}, {0, 2, 3, 4}}  -- (((A,E),(C,D)),B)
  | 73 => hierarchyOf {{1, 2}, {3, 4}, {1, 2, 3, 4}}  -- (((B,C),(D,E)),A)
  | 74 => hierarchyOf {{1, 3}, {2, 4}, {1, 2, 3, 4}}  -- (((B,D),(C,E)),A)
  | 75 => hierarchyOf {{1, 4}, {2, 3}, {1, 2, 3, 4}}  -- (((B,E),(C,D)),A)
  | 76 => hierarchyOf {{0, 1}, {3, 4}, {0, 1, 2}}  -- (((A,B),C),(D,E))
  | 77 => hierarchyOf {{0, 2}, {3, 4}, {0, 1, 2}}  -- (((A,C),B),(D,E))
  | 78 => hierarchyOf {{1, 2}, {3, 4}, {0, 1, 2}}  -- (((B,C),A),(D,E))
  | 79 => hierarchyOf {{0, 1}, {2, 4}, {0, 1, 3}}  -- (((A,B),D),(C,E))
  | 80 => hierarchyOf {{0, 3}, {2, 4}, {0, 1, 3}}  -- (((A,D),B),(C,E))
  | 81 => hierarchyOf {{1, 3}, {2, 4}, {0, 1, 3}}  -- (((B,D),A),(C,E))
  | 82 => hierarchyOf {{0, 2}, {1, 4}, {0, 2, 3}}  -- (((A,C),D),(B,E))
  | 83 => hierarchyOf {{0, 3}, {1, 4}, {0, 2, 3}}  -- (((A,D),C),(B,E))
  | 84 => hierarchyOf {{1, 4}, {2, 3}, {0, 2, 3}}  -- (((C,D),A),(B,E))
  | 85 => hierarchyOf {{0, 4}, {1, 2}, {1, 2, 3}}  -- (((B,C),D),(A,E))
  | 86 => hierarchyOf {{0, 4}, {1, 3}, {1, 2, 3}}  -- (((B,D),C),(A,E))
  | 87 => hierarchyOf {{0, 4}, {2, 3}, {1, 2, 3}}  -- (((C,D),B),(A,E))
  | 88 => hierarchyOf {{0, 1}, {2, 3}, {0, 1, 4}}  -- (((A,B),E),(C,D))
  | 89 => hierarchyOf {{0, 4}, {2, 3}, {0, 1, 4}}  -- (((A,E),B),(C,D))
  | 90 => hierarchyOf {{1, 4}, {2, 3}, {0, 1, 4}}  -- (((B,E),A),(C,D))
  | 91 => hierarchyOf {{0, 2}, {1, 3}, {0, 2, 4}}  -- (((A,C),E),(B,D))
  | 92 => hierarchyOf {{0, 4}, {1, 3}, {0, 2, 4}}  -- (((A,E),C),(B,D))
  | 93 => hierarchyOf {{1, 3}, {2, 4}, {0, 2, 4}}  -- (((C,E),A),(B,D))
  | 94 => hierarchyOf {{0, 3}, {1, 2}, {1, 2, 4}}  -- (((B,C),E),(A,D))
  | 95 => hierarchyOf {{0, 3}, {1, 4}, {1, 2, 4}}  -- (((B,E),C),(A,D))
  | 96 => hierarchyOf {{0, 3}, {2, 4}, {1, 2, 4}}  -- (((C,E),B),(A,D))
  | 97 => hierarchyOf {{0, 3}, {1, 2}, {0, 3, 4}}  -- (((A,D),E),(B,C))
  | 98 => hierarchyOf {{0, 4}, {1, 2}, {0, 3, 4}}  -- (((A,E),D),(B,C))
  | 99 => hierarchyOf {{1, 2}, {3, 4}, {0, 3, 4}}  -- (((D,E),A),(B,C))
  | 100 => hierarchyOf {{0, 2}, {1, 3}, {1, 3, 4}}  -- (((B,D),E),(A,C))
  | 101 => hierarchyOf {{0, 2}, {1, 4}, {1, 3, 4}}  -- (((B,E),D),(A,C))
  | 102 => hierarchyOf {{0, 2}, {3, 4}, {1, 3, 4}}  -- (((D,E),B),(A,C))
  | 103 => hierarchyOf {{0, 1}, {2, 3}, {2, 3, 4}}  -- (((C,D),E),(A,B))
  | 104 => hierarchyOf {{0, 1}, {2, 4}, {2, 3, 4}}  -- (((C,E),D),(A,B))
  | 105 => hierarchyOf {{0, 1}, {3, 4}, {2, 3, 4}}  -- (((D,E),C),(A,B))
  | _ => ∅

/-- `r σ j = ℙ_σ(R_j)`, the probability of the rooted gene tree `R_j`. -/
noncomputable def r (σ : SpeciesTree (Fin 5)) (j : ℕ) : ℝ :=
  σ.rootedDist id (R5 j)

/-- **Table 4.** The trees `R₁, …, R₁₀₅` are distinct, and they are exactly the rooted binary
trees on five taxa. -/
theorem table4 :
    Set.InjOn R5 (Icc 1 105 : Finset ℕ) ∧
      ∀ G : Finset (Finset (Fin 5)),
        (∃ τ : SpeciesTree (Fin 5), τ.clusters = G ∧ τ.IsBinary) ↔ ∃ j ∈ Icc 1 105, R5 j = G := by
  sorry

/-- **Table 5.** Each unrooted gene tree probability `u_i = ℙ(T_i)` is the sum of the
probabilities of its seven rooted versions listed in the table. -/
theorem table5 (σ : SpeciesTree (Fin 5)) :
    u σ 1 = r σ 1 + r σ 2 + r σ 59 + r σ 60 + r σ 67 + r σ 76 + r σ 105 ∧
    u σ 2 = r σ 3 + r σ 4 + r σ 53 + r σ 54 + r σ 64 + r σ 79 + r σ 104 ∧
    u σ 3 = r σ 5 + r σ 6 + r σ 47 + r σ 48 + r σ 61 + r σ 88 + r σ 103 ∧
    u σ 4 = r σ 7 + r σ 8 + r σ 57 + r σ 58 + r σ 70 + r σ 77 + r σ 102 ∧
    u σ 5 = r σ 9 + r σ 10 + r σ 41 + r σ 42 + r σ 65 + r σ 82 + r σ 101 ∧
    u σ 6 = r σ 11 + r σ 12 + r σ 35 + r σ 36 + r σ 62 + r σ 91 + r σ 100 ∧
    u σ 7 = r σ 13 + r σ 14 + r σ 51 + r σ 52 + r σ 71 + r σ 80 + r σ 96 ∧
    u σ 8 = r σ 15 + r σ 16 + r σ 39 + r σ 40 + r σ 68 + r σ 83 + r σ 95 ∧
    u σ 9 = r σ 17 + r σ 18 + r σ 29 + r σ 30 + r σ 63 + r σ 94 + r σ 97 ∧
    u σ 10 = r σ 19 + r σ 20 + r σ 45 + r σ 46 + r σ 72 + r σ 87 + r σ 89 ∧
    u σ 11 = r σ 21 + r σ 22 + r σ 33 + r σ 34 + r σ 69 + r σ 86 + r σ 92 ∧
    u σ 12 = r σ 23 + r σ 24 + r σ 27 + r σ 28 + r σ 66 + r σ 85 + r σ 98 ∧
    u σ 13 = r σ 25 + r σ 26 + r σ 55 + r σ 56 + r σ 73 + r σ 78 + r σ 99 ∧
    u σ 14 = r σ 31 + r σ 32 + r σ 49 + r σ 50 + r σ 74 + r σ 81 + r σ 93 ∧
    u σ 15 = r σ 37 + r σ 38 + r σ 43 + r σ 44 + r σ 75 + r σ 84 + r σ 90 := by
  sorry

end ADR11
