#!/usr/bin/env python3
"""Generate ADR11/Rootings/Statements.lean: the unrooted gene tree distributions of every rooting
of the standard unrooted trees on four and five taxa (`ADR11.rootings4`, `ADR11.rootings5`).

Usage: python3 scripts/gen_rootings.py > ADR11/Rootings/Statements.lean

The formulas are computed exactly (sympy) by `scripts/msc_model.py`, an independent
implementation of the multispecies coalescent (Tavare's g_ij and the jump chain on forests); the
Lean file only states them, and the proofs are separate. Each statement gives the probabilities
of all gene trees in terms of `exp (-τ.length C)` for the internal clusters `C` of the rooting."""
import sys
import sympy as sp
sys.path.insert(0, __import__('os').path.dirname(__file__))
from msc_model import unrooted_dist, nontrivial_splits

LET = 'abcde'

def tree_from_clusters(n, clusters, sym):
    """Nested tuple tree for msc_model from a hierarchy (nontrivial clusters as tuples)."""
    cl = sorted(set(clusters), key=len)
    def build(A):
        kids = [C for C in cl if set(C) < set(A) and not any(set(C) < set(D) < set(A) for D in cl)]
        covered = set().union(*[set(C) for C in kids]) if kids else set()
        ch = [build(C) for C in kids] + [LET[i] for i in sorted(set(A) - covered)]
        T = None if len(A) == n else sym[A]
        return (tuple(ch), T)
    return build(tuple(range(n)))

def name(C):
    return 'X' + ''.join(str(i) for i in C)

def lean_poly(expr, syms):
    expr = sp.expand(expr)
    if expr == 0:
        return '0'
    poly = sp.Poly(expr, *syms) if syms else None
    terms = poly.terms() if poly is not None else [((), expr)]
    out = []
    for monom, coeff in terms:
        coeff = sp.Rational(coeff)
        factors = []
        for s, e in zip(syms, monom):
            if e == 1: factors.append(str(s))
            elif e > 1: factors.append(f'{s} ^ {e}')
        num, den = coeff.p, coeff.q
        sign = '-' if num < 0 else '+'
        num = abs(num)
        if not factors:
            body = f'{num}' if den == 1 else f'{num} / {den}'
        else:
            c = '' if (num == 1 and den == 1) else (f'{num} * ' if den == 1 else f'{num} / {den} * ')
            body = c + ' * '.join(factors)
        out.append((sign, body))
    s = ('-' if out[0][0] == '-' else '') + out[0][1]
    for sign, body in out[1:]:
        s += f' {sign} {body}'
    return s

def lean_set(C):
    return '{' + ', '.join(str(i) for i in C) + '}'

def dist(n, clusters):
    syms = {C: sp.Symbol(name(C)) for C in clusters}
    tree = tree_from_clusters(n, clusters, syms)
    d = unrooted_dist(tree)
    allL = frozenset(LET[:n].upper())
    res = {}
    for T, w in d.items():
        sps = frozenset(frozenset(min(s, key=lambda x: sorted(x)) for s in [sp_]) for sp_ in nontrivial_splits(T, allL))
        key = frozenset(frozenset(min(sorted(map(sorted, S)))) for S in nontrivial_splits(T, allL))
        res[key] = sp.expand(res.get(key, 0) + w)
    return syms, res

# gene trees, keyed by the frozenset of the lexicographically smaller sides of their nontrivial splits
def side_key(sides, n):
    allL = set(LET[:n].upper())
    ks = []
    for A in sides:
        A = set(LET[i].upper() for i in A)
        B = allL - A
        ks.append(frozenset(min(sorted(A), sorted(B))))
    return frozenset(ks)

T5 = {1: [(0,1),(0,1,2)], 2: [(0,1),(0,1,3)], 3: [(0,1),(0,1,4)], 4: [(0,2),(0,1,2)], 5: [(0,2),(0,2,3)],
      6: [(0,2),(0,2,4)], 7: [(0,3),(0,1,3)], 8: [(0,3),(0,2,3)], 9: [(0,3),(0,3,4)], 10: [(0,4),(0,1,4)],
      11: [(0,4),(0,2,4)], 12: [(0,4),(0,3,4)], 13: [(1,2),(0,1,2)], 14: [(1,3),(0,1,3)], 15: [(1,4),(0,1,4)]}
Q4 = {'{{0, 1}}': [(0,1)], '{{0, 2}}': [(0,2)], '{{0, 3}}': [(0,3)]}

rootings4 = {1: [[(0,1),(0,1,2)], [(0,1),(0,1,3)], [(2,3),(0,2,3)], [(2,3),(1,2,3)], [(0,1),(2,3)], [(0,1)], [(2,3)]],
             0: [[], [(0,1,2)], [(0,1,3)], [(0,2,3)], [(1,2,3)]]}
rootings5 = {2: [[(0,1),(0,1,2),(0,1,2,3)], [(0,1),(0,1,2),(0,1,2,4)], [(3,4),(2,3,4),(1,2,3,4)], [(3,4),(2,3,4),(0,2,3,4)],
                 [(0,1),(3,4),(0,1,3,4)], [(0,1),(0,1,2),(3,4)], [(0,1),(3,4),(2,3,4)], [(0,1),(3,4)], [(0,1),(0,1,2)], [(3,4),(2,3,4)]],
             1: [[(0,1)], [(2,3,4)], [(0,1),(2,3,4)], [(2,3,4),(1,2,3,4)], [(2,3,4),(0,2,3,4)], [(0,1),(0,1,3,4)], [(0,1),(0,1,2,4)], [(0,1),(0,1,2,3)]],
             0: [[], [(1,2,3,4)], [(0,2,3,4)], [(0,1,3,4)], [(0,1,2,4)], [(0,1,2,3)]]}

def hier(clusters):
    return 'hierarchyOf {' + ', '.join(lean_set(C) for C in clusters) + '}' if clusters else 'hierarchyOf ∅'

print('''module

public import ADR11.SmallTrees

/-!
# The gene tree distributions of all rootings of the standard unrooted trees on four and five taxa

This file is generated by `scripts/gen_rootings.py`; do not edit it by hand. The formulas were
computed exactly by an independent implementation of the model (`scripts/msc_model.py`).

For each hierarchy `H` in `ADR11.rootings4 k` (four taxa) or `ADR11.rootings5 k` (five taxa), the
theorem `rootingDist4_k_j` / `rootingDist5_k_j` (`j` = position of `H` in the list) gives the
probability of every unrooted gene tree of a species tree with clusters `H`, as a polynomial in
`exp (-τ.length C)` for the internal clusters `C` of `H` (`XC` in the statements, e.g. `X012` for
the cluster `{0, 1, 2}`). On four taxa the gene trees are `treeOfClusters {{0, 1}}`,
`treeOfClusters {{0, 2}}`, `treeOfClusters {{0, 3}}`; on five taxa they are `T5 1, …, T5 15`.
`unrootedDist_eq_zero_four`, `unrootedDist_eq_zero_five`: every other unrooted tree has
probability `0`.
-/

@[expose] public section

namespace ADR11

open Finset Real
''')
print('''/-- On four taxa, only the three quartet trees have positive probability. -/
theorem unrootedDist_eq_zero_four (τ : SpeciesTree (Fin 4)) (T : Finset (Finset (Fin 4)))
    (hT : T ≠ treeOfClusters {{0, 1}} ∧ T ≠ treeOfClusters {{0, 2}} ∧ T ≠ treeOfClusters {{0, 3}}) :
    τ.unrootedDist id T = 0 := by
  sorry

/-- On five taxa, only the fifteen trees `T5 i` have positive probability. -/
theorem unrootedDist_eq_zero_five (τ : SpeciesTree (Fin 5)) (T : Finset (Finset (Fin 5)))
    (hT : ∀ i ∈ Icc 1 15, T ≠ T5 i) : τ.unrootedDist id T = 0 := by
  sorry
''')
for k in [1, 0]:
    for j, cl in enumerate(rootings4[k]):
        syms, res = dist(4, cl)
        symlist = [syms[C] for C in sorted(cl, key=lambda c: (len(c), c))]
        lines = [f'/-- The rooting `{hier(cl)}` of `U4 {k}`. -/',
                 f'theorem rootingDist4_{k}_{j} (τ : SpeciesTree (Fin 4)) (hτ : τ.clusters = {hier(cl)}) :']
        used = set().union(*[sp.sympify(res.get(side_key(sd, 4), 0)).free_symbols for sd in Q4.values()])
        lets = [f'    let {name(C)} := exp (-τ.length {lean_set(C)})' for C in sorted(cl, key=lambda c: (len(c), c)) if syms[C] in used]
        concl = []
        for tname, sides in Q4.items():
            key = side_key(sides, 4)
            concl.append(f'τ.unrootedDist id (treeOfClusters {tname}) = {lean_poly(res.get(key, 0), symlist)}')
        print('\n'.join(lines + lets) + '\n    ' + ' ∧\n    '.join(concl) + ' := by\n  sorry\n')
for k in [2, 1, 0]:
    for j, cl in enumerate(rootings5[k]):
        syms, res = dist(5, cl)
        symlist = [syms[C] for C in sorted(cl, key=lambda c: (len(c), c))]
        lines = [f'/-- The rooting `{hier(cl)}` of `U5 {k}`. -/',
                 f'theorem rootingDist5_{k}_{j} (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = {hier(cl)}) :']
        used = set().union(*[sp.sympify(res.get(side_key(T5[i], 5), 0)).free_symbols for i in range(1, 16)])
        lets = [f'    let {name(C)} := exp (-τ.length {lean_set(C)})' for C in sorted(cl, key=lambda c: (len(c), c)) if syms[C] in used]
        concl = []
        for i in range(1, 16):
            key = side_key(T5[i], 5)
            concl.append(f'u τ {i} = {lean_poly(res.get(key, 0), symlist)}')
        print('\n'.join(lines + lets) + '\n    ' + ' ∧\n    '.join(concl) + ' := by\n  sorry\n')
print('end ADR11')
