#!/usr/bin/env python3
"""Generate ADR11/AppendixA.lean (Tables 4 and 5 of the paper) from the paper's TeX source.

Usage: python3 scripts/gen_appendixA.py PAPER.tex > ADR11/AppendixA.lean
Each rooted tree R_j of Table 4 is written as `hierarchyOf C`, where `C` is the set of its
nontrivial clusters (taxa A..E = 0..4); Table 5's decompositions are copied as listed.

Proofs: the script also writes the codes of the clusters of each R_j (bit i of a code = taxon i),
`R5code j`, checked against `R5 j` by the kernel. `table4` then follows from the verified
enumeration of the binary hierarchies of `ADR11/Rootings/Support.lean` (`ADR11.root_table`), and
each line of `table5` from `ADR11.root_u_eq_sum`, with the indices `j` of the rooted versions of
`T_i` (sorted) checked by the kernel."""
import re, sys

tex = open(sys.argv[1]).read()
body4 = tex[tex.index(r'\label{T:5taxarooted}'):tex.index(r'\label{T:5taxaprobs}')]
R = {int(m.group(1)): m.group(2)
     for m in re.finditer(r'\$R_\{?(\d+)\}?\$\s*&\s*\$([^$]*)\$', body4)}
assert sorted(R) == list(range(1, 106))
start5 = tex.index(r'\label{T:5taxaprobs}')
body5 = tex[start5:tex.index(r'\end{table}', start5)]
dec = {}
for m in re.finditer(r'\$T_\{?(\d+)\}?\$\s*&\s*\$[^$]*\$,\s*\$[^$]*\$\s*&\s*\$u_\{?\d+\}?=\s*([^$]*)\$', body5):
    dec[int(m.group(1))] = [int(x) for x in re.findall(r'r_\{?(\d+)\}?', m.group(2))]
assert sorted(dec) == list(range(1, 16))

def clusters(newick):
    st, res = [], []
    for t in re.findall(r'[A-E]|\(|\)', newick):
        if t == '(':
            st.append(set())
        elif t == ')':
            c = st.pop()
            if 2 <= len(c) <= 4:
                res.append(sorted(c))
            if st:
                st[-1] |= c
        else:
            st[-1].add('ABCDE'.index(t))
    return sorted(res, key=lambda c: (len(c), c))

def code(c):
    return sum(1 << i for i in c)

def lean_set(c):
    return '{' + ', '.join(str(i) for i in c) + '}'

out = []
out.append('''module

public import ADR11.SmallTrees
public import ADR11.Rootings.Support

/-!
# Appendix A: the rooted and unrooted 5-taxon gene trees (Tables 4 and 5)

This file is generated by `scripts/gen_appendixA.py` from the paper's TeX source; do not edit it
by hand.

* `R5 j` (`1 ≤ j ≤ 105`): the rooted gene tree `R_j` of Table 4, as `hierarchyOf` its nontrivial
  clusters (taxa `A, …, E` are `0, …, 4`).
* `table4`: the `R_j` are distinct, each is a rooted binary tree, and every rooted binary tree on
  five taxa is one of them.
* `table5`: each unrooted gene tree probability `u_i` is the sum of the seven rooted gene tree
  probabilities `r_j = ℙ(R_j)` listed in Table 5.

The proofs use the codes `R5code j` of the clusters of `R5 j` (bit `i` of a code is taxon `i`) and
the verified enumeration of the binary hierarchies of `ADR11.Rootings.Support`.
-/

@[expose] public section

namespace ADR11

open Finset

/-- The rooted 5-taxon gene trees `R₁, …, R₁₀₅` of Table 4. -/
def R5 : ℕ → Finset (Finset (Fin 5))''')
for j in range(1, 106):
    cs = clusters(R[j])
    out.append(f'  | {j} => hierarchyOf {{{", ".join(lean_set(c) for c in cs)}}}  -- {R[j]}')
out.append('  | _ => ∅')
out.append('''
/-- `r σ j = ℙ_σ(R_j)`, the probability of the rooted gene tree `R_j`. -/
noncomputable def r (σ : SpeciesTree (Fin 5)) (j : ℕ) : ℝ :=
  σ.rootedDist id (R5 j)

/-- The codes of the clusters of `R5 j` (bit `i` of a code is taxon `i`): the nontrivial clusters,
the singletons and the root. -/
private def R5code : ℕ → List ℕ''')
for j in range(1, 106):
    cs = clusters(R[j])
    out.append(f'  | {j} => [{", ".join(str(code(c)) for c in cs)}, 1, 2, 4, 8, 16, 31]')
out.append('''  | _ => []

private theorem R5_eq_decF : ∀ j ∈ Icc 1 105, R5 j = Computation.decF 5 (R5code j) := by
  decide +kernel

private theorem R5_tableB : root_tableB 5 ((List.range' 1 105).map R5code) = true := by
  decide +kernel

/-- **Table 4.** The trees `R₁, …, R₁₀₅` are distinct, and they are exactly the rooted binary
trees on five taxa. -/
theorem table4 :
    Set.InjOn R5 (Icc 1 105 : Finset ℕ) ∧
      ∀ G : Finset (Finset (Fin 5)),
        (∃ τ : SpeciesTree (Fin 5), τ.clusters = G ∧ τ.IsBinary) ↔ ∃ j ∈ Icc 1 105, R5 j = G := by
  exact root_table R5 R5code 105 R5_eq_decF R5_tableB

/-- **Table 5.** Each unrooted gene tree probability `u_i = ℙ(T_i)` is the sum of the
probabilities of its seven rooted versions listed in the table. -/
theorem table5 (σ : SpeciesTree (Fin 5)) :''')
lines = []
for i in range(1, 16):
    js = dec[i]
    lines.append(f'    u σ {i} = ' + ' + '.join(f'r σ {j}' for j in js))
proof = ['  have h := fun (i : ℕ) (hi : i ∈ Icc 1 15) (js : List ℕ) hjs =>',
         '    root_u_eq_sum σ R5 R5code 105 R5_eq_decF R5_tableB (i := i) hi (js := js) hjs',
         '  refine ⟨' + ', '.join(['?_'] * 15) + '⟩']
for i in range(1, 16):
    js = sorted(dec[i])
    proof.append(f'  · rw [h {i} (by decide) [{", ".join(map(str, js))}] (by decide +kernel)]')
    proof.append('    simp only [r, List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]')
    proof.append('    ring')
out.append(' ∧\n'.join(lines) + ' := by\n' + '\n'.join(proof) + '\n\nend ADR11')
print('\n'.join(out))
