module

public import ADR11.SmallTrees

/-!
# The gene tree distributions of all rootings of the standard unrooted trees on four and five taxa

This file is generated by `scripts/gen_rootings.py`; do not edit it by hand. The formulas were
computed exactly by an independent implementation of the model (`scripts/msc_model.py`).

For each hierarchy `H` in `ADR11.rootings4 k` (four taxa) or `ADR11.rootings5 k` (five taxa), the
theorem `rootingDist4_k_j` / `rootingDist5_k_j` (`j` = position of `H` in the list) gives the
probability of every unrooted gene tree of a species tree with clusters `H`, as a polynomial in
`exp (-τ.length C)` for the internal clusters `C` of `H` (`XC` in the statements, e.g. `X012` for
the cluster `{0, 1, 2}`). On four taxa the gene trees are `treeOfClusters {{0, 1}}`,
`treeOfClusters {{0, 2}}`, `treeOfClusters {{0, 3}}`; on five taxa they are `T5 1, …, T5 15`.
`unrootedDist_eq_zero_four`, `unrootedDist_eq_zero_five`: every other unrooted tree has
probability `0`.
-/

@[expose] public section

namespace ADR11

open Finset Real

/-- On four taxa, only the three quartet trees have positive probability. -/
theorem unrootedDist_eq_zero_four (τ : SpeciesTree (Fin 4)) (T : Finset (Finset (Fin 4)))
    (hT : T ≠ treeOfClusters {{0, 1}} ∧ T ≠ treeOfClusters {{0, 2}} ∧ T ≠ treeOfClusters {{0, 3}}) :
    τ.unrootedDist id T = 0 := by
  sorry

/-- On five taxa, only the fifteen trees `T5 i` have positive probability. -/
theorem unrootedDist_eq_zero_five (τ : SpeciesTree (Fin 5)) (T : Finset (Finset (Fin 5)))
    (hT : ∀ i ∈ Icc 1 15, T ≠ T5 i) : τ.unrootedDist id T = 0 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {0, 1, 2}}` of `U4 1`. -/
theorem rootingDist4_1_0 (τ : SpeciesTree (Fin 4)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {0, 1, 2}}) :
    let X01 := exp (-τ.length {0, 1})
    τ.unrootedDist id (treeOfClusters {{0, 1}}) = -2 / 3 * X01 + 1 ∧
    τ.unrootedDist id (treeOfClusters {{0, 2}}) = 1 / 3 * X01 ∧
    τ.unrootedDist id (treeOfClusters {{0, 3}}) = 1 / 3 * X01 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {0, 1, 3}}` of `U4 1`. -/
theorem rootingDist4_1_1 (τ : SpeciesTree (Fin 4)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {0, 1, 3}}) :
    let X01 := exp (-τ.length {0, 1})
    τ.unrootedDist id (treeOfClusters {{0, 1}}) = -2 / 3 * X01 + 1 ∧
    τ.unrootedDist id (treeOfClusters {{0, 2}}) = 1 / 3 * X01 ∧
    τ.unrootedDist id (treeOfClusters {{0, 3}}) = 1 / 3 * X01 := by
  sorry

/-- The rooting `hierarchyOf {{2, 3}, {0, 2, 3}}` of `U4 1`. -/
theorem rootingDist4_1_2 (τ : SpeciesTree (Fin 4)) (hτ : τ.clusters = hierarchyOf {{2, 3}, {0, 2, 3}}) :
    let X23 := exp (-τ.length {2, 3})
    τ.unrootedDist id (treeOfClusters {{0, 1}}) = -2 / 3 * X23 + 1 ∧
    τ.unrootedDist id (treeOfClusters {{0, 2}}) = 1 / 3 * X23 ∧
    τ.unrootedDist id (treeOfClusters {{0, 3}}) = 1 / 3 * X23 := by
  sorry

/-- The rooting `hierarchyOf {{2, 3}, {1, 2, 3}}` of `U4 1`. -/
theorem rootingDist4_1_3 (τ : SpeciesTree (Fin 4)) (hτ : τ.clusters = hierarchyOf {{2, 3}, {1, 2, 3}}) :
    let X23 := exp (-τ.length {2, 3})
    τ.unrootedDist id (treeOfClusters {{0, 1}}) = -2 / 3 * X23 + 1 ∧
    τ.unrootedDist id (treeOfClusters {{0, 2}}) = 1 / 3 * X23 ∧
    τ.unrootedDist id (treeOfClusters {{0, 3}}) = 1 / 3 * X23 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {2, 3}}` of `U4 1`. -/
theorem rootingDist4_1_4 (τ : SpeciesTree (Fin 4)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {2, 3}}) :
    let X01 := exp (-τ.length {0, 1})
    let X23 := exp (-τ.length {2, 3})
    τ.unrootedDist id (treeOfClusters {{0, 1}}) = -2 / 3 * X01 * X23 + 1 ∧
    τ.unrootedDist id (treeOfClusters {{0, 2}}) = 1 / 3 * X01 * X23 ∧
    τ.unrootedDist id (treeOfClusters {{0, 3}}) = 1 / 3 * X01 * X23 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}}` of `U4 1`. -/
theorem rootingDist4_1_5 (τ : SpeciesTree (Fin 4)) (hτ : τ.clusters = hierarchyOf {{0, 1}}) :
    let X01 := exp (-τ.length {0, 1})
    τ.unrootedDist id (treeOfClusters {{0, 1}}) = -2 / 3 * X01 + 1 ∧
    τ.unrootedDist id (treeOfClusters {{0, 2}}) = 1 / 3 * X01 ∧
    τ.unrootedDist id (treeOfClusters {{0, 3}}) = 1 / 3 * X01 := by
  sorry

/-- The rooting `hierarchyOf {{2, 3}}` of `U4 1`. -/
theorem rootingDist4_1_6 (τ : SpeciesTree (Fin 4)) (hτ : τ.clusters = hierarchyOf {{2, 3}}) :
    let X23 := exp (-τ.length {2, 3})
    τ.unrootedDist id (treeOfClusters {{0, 1}}) = -2 / 3 * X23 + 1 ∧
    τ.unrootedDist id (treeOfClusters {{0, 2}}) = 1 / 3 * X23 ∧
    τ.unrootedDist id (treeOfClusters {{0, 3}}) = 1 / 3 * X23 := by
  sorry

/-- The rooting `hierarchyOf ∅` of `U4 0`. -/
theorem rootingDist4_0_0 (τ : SpeciesTree (Fin 4)) (hτ : τ.clusters = hierarchyOf ∅) :
    τ.unrootedDist id (treeOfClusters {{0, 1}}) = 1 / 3 ∧
    τ.unrootedDist id (treeOfClusters {{0, 2}}) = 1 / 3 ∧
    τ.unrootedDist id (treeOfClusters {{0, 3}}) = 1 / 3 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1, 2}}` of `U4 0`. -/
theorem rootingDist4_0_1 (τ : SpeciesTree (Fin 4)) (hτ : τ.clusters = hierarchyOf {{0, 1, 2}}) :
    τ.unrootedDist id (treeOfClusters {{0, 1}}) = 1 / 3 ∧
    τ.unrootedDist id (treeOfClusters {{0, 2}}) = 1 / 3 ∧
    τ.unrootedDist id (treeOfClusters {{0, 3}}) = 1 / 3 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1, 3}}` of `U4 0`. -/
theorem rootingDist4_0_2 (τ : SpeciesTree (Fin 4)) (hτ : τ.clusters = hierarchyOf {{0, 1, 3}}) :
    τ.unrootedDist id (treeOfClusters {{0, 1}}) = 1 / 3 ∧
    τ.unrootedDist id (treeOfClusters {{0, 2}}) = 1 / 3 ∧
    τ.unrootedDist id (treeOfClusters {{0, 3}}) = 1 / 3 := by
  sorry

/-- The rooting `hierarchyOf {{0, 2, 3}}` of `U4 0`. -/
theorem rootingDist4_0_3 (τ : SpeciesTree (Fin 4)) (hτ : τ.clusters = hierarchyOf {{0, 2, 3}}) :
    τ.unrootedDist id (treeOfClusters {{0, 1}}) = 1 / 3 ∧
    τ.unrootedDist id (treeOfClusters {{0, 2}}) = 1 / 3 ∧
    τ.unrootedDist id (treeOfClusters {{0, 3}}) = 1 / 3 := by
  sorry

/-- The rooting `hierarchyOf {{1, 2, 3}}` of `U4 0`. -/
theorem rootingDist4_0_4 (τ : SpeciesTree (Fin 4)) (hτ : τ.clusters = hierarchyOf {{1, 2, 3}}) :
    τ.unrootedDist id (treeOfClusters {{0, 1}}) = 1 / 3 ∧
    τ.unrootedDist id (treeOfClusters {{0, 2}}) = 1 / 3 ∧
    τ.unrootedDist id (treeOfClusters {{0, 3}}) = 1 / 3 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {0, 1, 2}, {0, 1, 2, 3}}` of `U5 2`. -/
theorem rootingDist5_2_0 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {0, 1, 2}, {0, 1, 2, 3}}) :
    let X01 := exp (-τ.length {0, 1})
    let X012 := exp (-τ.length {0, 1, 2})
    let X0123 := exp (-τ.length {0, 1, 2, 3})
    u τ 1 = 1 / 90 * X01 * X012 ^ 3 * X0123 ^ 6 + 1 / 18 * X01 * X012 ^ 3 + 1 / 3 * X01 * X012 - 2 / 3 * X01 - 2 / 3 * X012 + 1 ∧
    u τ 2 = 1 / 90 * X01 * X012 ^ 3 * X0123 ^ 6 - 1 / 9 * X01 * X012 ^ 3 - 1 / 6 * X01 * X012 + 1 / 3 * X012 ∧
    u τ 3 = -2 / 45 * X01 * X012 ^ 3 * X0123 ^ 6 - 1 / 18 * X01 * X012 ^ 3 - 1 / 6 * X01 * X012 + 1 / 3 * X012 ∧
    u τ 4 = 1 / 90 * X01 * X012 ^ 3 * X0123 ^ 6 + 1 / 18 * X01 * X012 ^ 3 - 1 / 3 * X01 * X012 + 1 / 3 * X01 ∧
    u τ 5 = 1 / 90 * X01 * X012 ^ 3 * X0123 ^ 6 - 1 / 9 * X01 * X012 ^ 3 + 1 / 6 * X01 * X012 ∧
    u τ 6 = -2 / 45 * X01 * X012 ^ 3 * X0123 ^ 6 - 1 / 18 * X01 * X012 ^ 3 + 1 / 6 * X01 * X012 ∧
    u τ 7 = 1 / 90 * X01 * X012 ^ 3 * X0123 ^ 6 + 1 / 18 * X01 * X012 ^ 3 ∧
    u τ 8 = 1 / 90 * X01 * X012 ^ 3 * X0123 ^ 6 + 1 / 18 * X01 * X012 ^ 3 ∧
    u τ 9 = -2 / 45 * X01 * X012 ^ 3 * X0123 ^ 6 - 1 / 18 * X01 * X012 ^ 3 + 1 / 6 * X01 * X012 ∧
    u τ 10 = 1 / 90 * X01 * X012 ^ 3 * X0123 ^ 6 + 1 / 18 * X01 * X012 ^ 3 ∧
    u τ 11 = 1 / 90 * X01 * X012 ^ 3 * X0123 ^ 6 + 1 / 18 * X01 * X012 ^ 3 ∧
    u τ 12 = 1 / 90 * X01 * X012 ^ 3 * X0123 ^ 6 - 1 / 9 * X01 * X012 ^ 3 + 1 / 6 * X01 * X012 ∧
    u τ 13 = 1 / 90 * X01 * X012 ^ 3 * X0123 ^ 6 + 1 / 18 * X01 * X012 ^ 3 - 1 / 3 * X01 * X012 + 1 / 3 * X01 ∧
    u τ 14 = 1 / 90 * X01 * X012 ^ 3 * X0123 ^ 6 + 1 / 18 * X01 * X012 ^ 3 ∧
    u τ 15 = 1 / 90 * X01 * X012 ^ 3 * X0123 ^ 6 + 1 / 18 * X01 * X012 ^ 3 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {0, 1, 2}, {0, 1, 2, 4}}` of `U5 2`. -/
theorem rootingDist5_2_1 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {0, 1, 2}, {0, 1, 2, 4}}) :
    let X01 := exp (-τ.length {0, 1})
    let X012 := exp (-τ.length {0, 1, 2})
    let X0124 := exp (-τ.length {0, 1, 2, 4})
    u τ 1 = 1 / 90 * X01 * X012 ^ 3 * X0124 ^ 6 + 1 / 18 * X01 * X012 ^ 3 + 1 / 3 * X01 * X012 - 2 / 3 * X01 - 2 / 3 * X012 + 1 ∧
    u τ 2 = -2 / 45 * X01 * X012 ^ 3 * X0124 ^ 6 - 1 / 18 * X01 * X012 ^ 3 - 1 / 6 * X01 * X012 + 1 / 3 * X012 ∧
    u τ 3 = 1 / 90 * X01 * X012 ^ 3 * X0124 ^ 6 - 1 / 9 * X01 * X012 ^ 3 - 1 / 6 * X01 * X012 + 1 / 3 * X012 ∧
    u τ 4 = 1 / 90 * X01 * X012 ^ 3 * X0124 ^ 6 + 1 / 18 * X01 * X012 ^ 3 - 1 / 3 * X01 * X012 + 1 / 3 * X01 ∧
    u τ 5 = -2 / 45 * X01 * X012 ^ 3 * X0124 ^ 6 - 1 / 18 * X01 * X012 ^ 3 + 1 / 6 * X01 * X012 ∧
    u τ 6 = 1 / 90 * X01 * X012 ^ 3 * X0124 ^ 6 - 1 / 9 * X01 * X012 ^ 3 + 1 / 6 * X01 * X012 ∧
    u τ 7 = 1 / 90 * X01 * X012 ^ 3 * X0124 ^ 6 + 1 / 18 * X01 * X012 ^ 3 ∧
    u τ 8 = 1 / 90 * X01 * X012 ^ 3 * X0124 ^ 6 + 1 / 18 * X01 * X012 ^ 3 ∧
    u τ 9 = 1 / 90 * X01 * X012 ^ 3 * X0124 ^ 6 - 1 / 9 * X01 * X012 ^ 3 + 1 / 6 * X01 * X012 ∧
    u τ 10 = 1 / 90 * X01 * X012 ^ 3 * X0124 ^ 6 + 1 / 18 * X01 * X012 ^ 3 ∧
    u τ 11 = 1 / 90 * X01 * X012 ^ 3 * X0124 ^ 6 + 1 / 18 * X01 * X012 ^ 3 ∧
    u τ 12 = -2 / 45 * X01 * X012 ^ 3 * X0124 ^ 6 - 1 / 18 * X01 * X012 ^ 3 + 1 / 6 * X01 * X012 ∧
    u τ 13 = 1 / 90 * X01 * X012 ^ 3 * X0124 ^ 6 + 1 / 18 * X01 * X012 ^ 3 - 1 / 3 * X01 * X012 + 1 / 3 * X01 ∧
    u τ 14 = 1 / 90 * X01 * X012 ^ 3 * X0124 ^ 6 + 1 / 18 * X01 * X012 ^ 3 ∧
    u τ 15 = 1 / 90 * X01 * X012 ^ 3 * X0124 ^ 6 + 1 / 18 * X01 * X012 ^ 3 := by
  sorry

/-- The rooting `hierarchyOf {{3, 4}, {2, 3, 4}, {1, 2, 3, 4}}` of `U5 2`. -/
theorem rootingDist5_2_2 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{3, 4}, {2, 3, 4}, {1, 2, 3, 4}}) :
    let X34 := exp (-τ.length {3, 4})
    let X234 := exp (-τ.length {2, 3, 4})
    let X1234 := exp (-τ.length {1, 2, 3, 4})
    u τ 1 = 1 / 90 * X34 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 + 1 / 3 * X34 * X234 - 2 / 3 * X34 - 2 / 3 * X234 + 1 ∧
    u τ 2 = 1 / 90 * X34 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 - 1 / 3 * X34 * X234 + 1 / 3 * X34 ∧
    u τ 3 = 1 / 90 * X34 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 - 1 / 3 * X34 * X234 + 1 / 3 * X34 ∧
    u τ 4 = 1 / 90 * X34 * X234 ^ 3 * X1234 ^ 6 - 1 / 9 * X34 * X234 ^ 3 - 1 / 6 * X34 * X234 + 1 / 3 * X234 ∧
    u τ 5 = 1 / 90 * X34 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 ∧
    u τ 6 = 1 / 90 * X34 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 ∧
    u τ 7 = 1 / 90 * X34 * X234 ^ 3 * X1234 ^ 6 - 1 / 9 * X34 * X234 ^ 3 + 1 / 6 * X34 * X234 ∧
    u τ 8 = 1 / 90 * X34 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 ∧
    u τ 9 = 1 / 90 * X34 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 ∧
    u τ 10 = 1 / 90 * X34 * X234 ^ 3 * X1234 ^ 6 - 1 / 9 * X34 * X234 ^ 3 + 1 / 6 * X34 * X234 ∧
    u τ 11 = 1 / 90 * X34 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 ∧
    u τ 12 = 1 / 90 * X34 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 ∧
    u τ 13 = -2 / 45 * X34 * X234 ^ 3 * X1234 ^ 6 - 1 / 18 * X34 * X234 ^ 3 - 1 / 6 * X34 * X234 + 1 / 3 * X234 ∧
    u τ 14 = -2 / 45 * X34 * X234 ^ 3 * X1234 ^ 6 - 1 / 18 * X34 * X234 ^ 3 + 1 / 6 * X34 * X234 ∧
    u τ 15 = -2 / 45 * X34 * X234 ^ 3 * X1234 ^ 6 - 1 / 18 * X34 * X234 ^ 3 + 1 / 6 * X34 * X234 := by
  sorry

/-- The rooting `hierarchyOf {{3, 4}, {2, 3, 4}, {0, 2, 3, 4}}` of `U5 2`. -/
theorem rootingDist5_2_3 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{3, 4}, {2, 3, 4}, {0, 2, 3, 4}}) :
    let X34 := exp (-τ.length {3, 4})
    let X234 := exp (-τ.length {2, 3, 4})
    let X0234 := exp (-τ.length {0, 2, 3, 4})
    u τ 1 = 1 / 90 * X34 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 + 1 / 3 * X34 * X234 - 2 / 3 * X34 - 2 / 3 * X234 + 1 ∧
    u τ 2 = 1 / 90 * X34 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 - 1 / 3 * X34 * X234 + 1 / 3 * X34 ∧
    u τ 3 = 1 / 90 * X34 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 - 1 / 3 * X34 * X234 + 1 / 3 * X34 ∧
    u τ 4 = -2 / 45 * X34 * X234 ^ 3 * X0234 ^ 6 - 1 / 18 * X34 * X234 ^ 3 - 1 / 6 * X34 * X234 + 1 / 3 * X234 ∧
    u τ 5 = 1 / 90 * X34 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 ∧
    u τ 6 = 1 / 90 * X34 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 ∧
    u τ 7 = -2 / 45 * X34 * X234 ^ 3 * X0234 ^ 6 - 1 / 18 * X34 * X234 ^ 3 + 1 / 6 * X34 * X234 ∧
    u τ 8 = 1 / 90 * X34 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 ∧
    u τ 9 = 1 / 90 * X34 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 ∧
    u τ 10 = -2 / 45 * X34 * X234 ^ 3 * X0234 ^ 6 - 1 / 18 * X34 * X234 ^ 3 + 1 / 6 * X34 * X234 ∧
    u τ 11 = 1 / 90 * X34 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 ∧
    u τ 12 = 1 / 90 * X34 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X34 * X234 ^ 3 ∧
    u τ 13 = 1 / 90 * X34 * X234 ^ 3 * X0234 ^ 6 - 1 / 9 * X34 * X234 ^ 3 - 1 / 6 * X34 * X234 + 1 / 3 * X234 ∧
    u τ 14 = 1 / 90 * X34 * X234 ^ 3 * X0234 ^ 6 - 1 / 9 * X34 * X234 ^ 3 + 1 / 6 * X34 * X234 ∧
    u τ 15 = 1 / 90 * X34 * X234 ^ 3 * X0234 ^ 6 - 1 / 9 * X34 * X234 ^ 3 + 1 / 6 * X34 * X234 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {3, 4}, {0, 1, 3, 4}}` of `U5 2`. -/
theorem rootingDist5_2_4 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {3, 4}, {0, 1, 3, 4}}) :
    let X01 := exp (-τ.length {0, 1})
    let X34 := exp (-τ.length {3, 4})
    let X0134 := exp (-τ.length {0, 1, 3, 4})
    u τ 1 = -2 / 45 * X01 * X34 * X0134 ^ 6 + 4 / 9 * X01 * X34 - 2 / 3 * X01 - 2 / 3 * X34 + 1 ∧
    u τ 2 = 1 / 90 * X01 * X34 * X0134 ^ 6 - 5 / 18 * X01 * X34 + 1 / 3 * X34 ∧
    u τ 3 = 1 / 90 * X01 * X34 * X0134 ^ 6 - 5 / 18 * X01 * X34 + 1 / 3 * X34 ∧
    u τ 4 = 1 / 90 * X01 * X34 * X0134 ^ 6 - 5 / 18 * X01 * X34 + 1 / 3 * X01 ∧
    u τ 5 = 1 / 90 * X01 * X34 * X0134 ^ 6 + 1 / 18 * X01 * X34 ∧
    u τ 6 = 1 / 90 * X01 * X34 * X0134 ^ 6 + 1 / 18 * X01 * X34 ∧
    u τ 7 = 1 / 90 * X01 * X34 * X0134 ^ 6 + 1 / 18 * X01 * X34 ∧
    u τ 8 = -2 / 45 * X01 * X34 * X0134 ^ 6 + 1 / 9 * X01 * X34 ∧
    u τ 9 = 1 / 90 * X01 * X34 * X0134 ^ 6 + 1 / 18 * X01 * X34 ∧
    u τ 10 = 1 / 90 * X01 * X34 * X0134 ^ 6 + 1 / 18 * X01 * X34 ∧
    u τ 11 = -2 / 45 * X01 * X34 * X0134 ^ 6 + 1 / 9 * X01 * X34 ∧
    u τ 12 = 1 / 90 * X01 * X34 * X0134 ^ 6 + 1 / 18 * X01 * X34 ∧
    u τ 13 = 1 / 90 * X01 * X34 * X0134 ^ 6 - 5 / 18 * X01 * X34 + 1 / 3 * X01 ∧
    u τ 14 = 1 / 90 * X01 * X34 * X0134 ^ 6 + 1 / 18 * X01 * X34 ∧
    u τ 15 = 1 / 90 * X01 * X34 * X0134 ^ 6 + 1 / 18 * X01 * X34 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {0, 1, 2}, {3, 4}}` of `U5 2`. -/
theorem rootingDist5_2_5 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {0, 1, 2}, {3, 4}}) :
    let X01 := exp (-τ.length {0, 1})
    let X34 := exp (-τ.length {3, 4})
    let X012 := exp (-τ.length {0, 1, 2})
    u τ 1 = 1 / 15 * X01 * X34 * X012 ^ 3 + 1 / 3 * X01 * X34 * X012 - 2 / 3 * X01 - 2 / 3 * X34 * X012 + 1 ∧
    u τ 2 = -1 / 10 * X01 * X34 * X012 ^ 3 - 1 / 6 * X01 * X34 * X012 + 1 / 3 * X34 * X012 ∧
    u τ 3 = -1 / 10 * X01 * X34 * X012 ^ 3 - 1 / 6 * X01 * X34 * X012 + 1 / 3 * X34 * X012 ∧
    u τ 4 = 1 / 15 * X01 * X34 * X012 ^ 3 - 1 / 3 * X01 * X34 * X012 + 1 / 3 * X01 ∧
    u τ 5 = -1 / 10 * X01 * X34 * X012 ^ 3 + 1 / 6 * X01 * X34 * X012 ∧
    u τ 6 = -1 / 10 * X01 * X34 * X012 ^ 3 + 1 / 6 * X01 * X34 * X012 ∧
    u τ 7 = 1 / 15 * X01 * X34 * X012 ^ 3 ∧
    u τ 8 = 1 / 15 * X01 * X34 * X012 ^ 3 ∧
    u τ 9 = -1 / 10 * X01 * X34 * X012 ^ 3 + 1 / 6 * X01 * X34 * X012 ∧
    u τ 10 = 1 / 15 * X01 * X34 * X012 ^ 3 ∧
    u τ 11 = 1 / 15 * X01 * X34 * X012 ^ 3 ∧
    u τ 12 = -1 / 10 * X01 * X34 * X012 ^ 3 + 1 / 6 * X01 * X34 * X012 ∧
    u τ 13 = 1 / 15 * X01 * X34 * X012 ^ 3 - 1 / 3 * X01 * X34 * X012 + 1 / 3 * X01 ∧
    u τ 14 = 1 / 15 * X01 * X34 * X012 ^ 3 ∧
    u τ 15 = 1 / 15 * X01 * X34 * X012 ^ 3 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {3, 4}, {2, 3, 4}}` of `U5 2`. -/
theorem rootingDist5_2_6 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {3, 4}, {2, 3, 4}}) :
    let X01 := exp (-τ.length {0, 1})
    let X34 := exp (-τ.length {3, 4})
    let X234 := exp (-τ.length {2, 3, 4})
    u τ 1 = 1 / 15 * X01 * X34 * X234 ^ 3 + 1 / 3 * X01 * X34 * X234 - 2 / 3 * X01 * X234 - 2 / 3 * X34 + 1 ∧
    u τ 2 = 1 / 15 * X01 * X34 * X234 ^ 3 - 1 / 3 * X01 * X34 * X234 + 1 / 3 * X34 ∧
    u τ 3 = 1 / 15 * X01 * X34 * X234 ^ 3 - 1 / 3 * X01 * X34 * X234 + 1 / 3 * X34 ∧
    u τ 4 = -1 / 10 * X01 * X34 * X234 ^ 3 - 1 / 6 * X01 * X34 * X234 + 1 / 3 * X01 * X234 ∧
    u τ 5 = 1 / 15 * X01 * X34 * X234 ^ 3 ∧
    u τ 6 = 1 / 15 * X01 * X34 * X234 ^ 3 ∧
    u τ 7 = -1 / 10 * X01 * X34 * X234 ^ 3 + 1 / 6 * X01 * X34 * X234 ∧
    u τ 8 = 1 / 15 * X01 * X34 * X234 ^ 3 ∧
    u τ 9 = 1 / 15 * X01 * X34 * X234 ^ 3 ∧
    u τ 10 = -1 / 10 * X01 * X34 * X234 ^ 3 + 1 / 6 * X01 * X34 * X234 ∧
    u τ 11 = 1 / 15 * X01 * X34 * X234 ^ 3 ∧
    u τ 12 = 1 / 15 * X01 * X34 * X234 ^ 3 ∧
    u τ 13 = -1 / 10 * X01 * X34 * X234 ^ 3 - 1 / 6 * X01 * X34 * X234 + 1 / 3 * X01 * X234 ∧
    u τ 14 = -1 / 10 * X01 * X34 * X234 ^ 3 + 1 / 6 * X01 * X34 * X234 ∧
    u τ 15 = -1 / 10 * X01 * X34 * X234 ^ 3 + 1 / 6 * X01 * X34 * X234 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {3, 4}}` of `U5 2`. -/
theorem rootingDist5_2_7 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {3, 4}}) :
    let X01 := exp (-τ.length {0, 1})
    let X34 := exp (-τ.length {3, 4})
    u τ 1 = 2 / 5 * X01 * X34 - 2 / 3 * X01 - 2 / 3 * X34 + 1 ∧
    u τ 2 = -4 / 15 * X01 * X34 + 1 / 3 * X34 ∧
    u τ 3 = -4 / 15 * X01 * X34 + 1 / 3 * X34 ∧
    u τ 4 = -4 / 15 * X01 * X34 + 1 / 3 * X01 ∧
    u τ 5 = 1 / 15 * X01 * X34 ∧
    u τ 6 = 1 / 15 * X01 * X34 ∧
    u τ 7 = 1 / 15 * X01 * X34 ∧
    u τ 8 = 1 / 15 * X01 * X34 ∧
    u τ 9 = 1 / 15 * X01 * X34 ∧
    u τ 10 = 1 / 15 * X01 * X34 ∧
    u τ 11 = 1 / 15 * X01 * X34 ∧
    u τ 12 = 1 / 15 * X01 * X34 ∧
    u τ 13 = -4 / 15 * X01 * X34 + 1 / 3 * X01 ∧
    u τ 14 = 1 / 15 * X01 * X34 ∧
    u τ 15 = 1 / 15 * X01 * X34 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {0, 1, 2}}` of `U5 2`. -/
theorem rootingDist5_2_8 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {0, 1, 2}}) :
    let X01 := exp (-τ.length {0, 1})
    let X012 := exp (-τ.length {0, 1, 2})
    u τ 1 = 1 / 15 * X01 * X012 ^ 3 + 1 / 3 * X01 * X012 - 2 / 3 * X01 - 2 / 3 * X012 + 1 ∧
    u τ 2 = -1 / 10 * X01 * X012 ^ 3 - 1 / 6 * X01 * X012 + 1 / 3 * X012 ∧
    u τ 3 = -1 / 10 * X01 * X012 ^ 3 - 1 / 6 * X01 * X012 + 1 / 3 * X012 ∧
    u τ 4 = 1 / 15 * X01 * X012 ^ 3 - 1 / 3 * X01 * X012 + 1 / 3 * X01 ∧
    u τ 5 = -1 / 10 * X01 * X012 ^ 3 + 1 / 6 * X01 * X012 ∧
    u τ 6 = -1 / 10 * X01 * X012 ^ 3 + 1 / 6 * X01 * X012 ∧
    u τ 7 = 1 / 15 * X01 * X012 ^ 3 ∧
    u τ 8 = 1 / 15 * X01 * X012 ^ 3 ∧
    u τ 9 = -1 / 10 * X01 * X012 ^ 3 + 1 / 6 * X01 * X012 ∧
    u τ 10 = 1 / 15 * X01 * X012 ^ 3 ∧
    u τ 11 = 1 / 15 * X01 * X012 ^ 3 ∧
    u τ 12 = -1 / 10 * X01 * X012 ^ 3 + 1 / 6 * X01 * X012 ∧
    u τ 13 = 1 / 15 * X01 * X012 ^ 3 - 1 / 3 * X01 * X012 + 1 / 3 * X01 ∧
    u τ 14 = 1 / 15 * X01 * X012 ^ 3 ∧
    u τ 15 = 1 / 15 * X01 * X012 ^ 3 := by
  sorry

/-- The rooting `hierarchyOf {{3, 4}, {2, 3, 4}}` of `U5 2`. -/
theorem rootingDist5_2_9 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{3, 4}, {2, 3, 4}}) :
    let X34 := exp (-τ.length {3, 4})
    let X234 := exp (-τ.length {2, 3, 4})
    u τ 1 = 1 / 15 * X34 * X234 ^ 3 + 1 / 3 * X34 * X234 - 2 / 3 * X34 - 2 / 3 * X234 + 1 ∧
    u τ 2 = 1 / 15 * X34 * X234 ^ 3 - 1 / 3 * X34 * X234 + 1 / 3 * X34 ∧
    u τ 3 = 1 / 15 * X34 * X234 ^ 3 - 1 / 3 * X34 * X234 + 1 / 3 * X34 ∧
    u τ 4 = -1 / 10 * X34 * X234 ^ 3 - 1 / 6 * X34 * X234 + 1 / 3 * X234 ∧
    u τ 5 = 1 / 15 * X34 * X234 ^ 3 ∧
    u τ 6 = 1 / 15 * X34 * X234 ^ 3 ∧
    u τ 7 = -1 / 10 * X34 * X234 ^ 3 + 1 / 6 * X34 * X234 ∧
    u τ 8 = 1 / 15 * X34 * X234 ^ 3 ∧
    u τ 9 = 1 / 15 * X34 * X234 ^ 3 ∧
    u τ 10 = -1 / 10 * X34 * X234 ^ 3 + 1 / 6 * X34 * X234 ∧
    u τ 11 = 1 / 15 * X34 * X234 ^ 3 ∧
    u τ 12 = 1 / 15 * X34 * X234 ^ 3 ∧
    u τ 13 = -1 / 10 * X34 * X234 ^ 3 - 1 / 6 * X34 * X234 + 1 / 3 * X234 ∧
    u τ 14 = -1 / 10 * X34 * X234 ^ 3 + 1 / 6 * X34 * X234 ∧
    u τ 15 = -1 / 10 * X34 * X234 ^ 3 + 1 / 6 * X34 * X234 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}}` of `U5 1`. -/
theorem rootingDist5_1_0 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1}}) :
    let X01 := exp (-τ.length {0, 1})
    u τ 1 = -4 / 15 * X01 + 1 / 3 ∧
    u τ 2 = -4 / 15 * X01 + 1 / 3 ∧
    u τ 3 = -4 / 15 * X01 + 1 / 3 ∧
    u τ 4 = 1 / 15 * X01 ∧
    u τ 5 = 1 / 15 * X01 ∧
    u τ 6 = 1 / 15 * X01 ∧
    u τ 7 = 1 / 15 * X01 ∧
    u τ 8 = 1 / 15 * X01 ∧
    u τ 9 = 1 / 15 * X01 ∧
    u τ 10 = 1 / 15 * X01 ∧
    u τ 11 = 1 / 15 * X01 ∧
    u τ 12 = 1 / 15 * X01 ∧
    u τ 13 = 1 / 15 * X01 ∧
    u τ 14 = 1 / 15 * X01 ∧
    u τ 15 = 1 / 15 * X01 := by
  sorry

/-- The rooting `hierarchyOf {{2, 3, 4}}` of `U5 1`. -/
theorem rootingDist5_1_1 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{2, 3, 4}}) :
    let X234 := exp (-τ.length {2, 3, 4})
    u τ 1 = 1 / 15 * X234 ^ 3 - 1 / 3 * X234 + 1 / 3 ∧
    u τ 2 = 1 / 15 * X234 ^ 3 - 1 / 3 * X234 + 1 / 3 ∧
    u τ 3 = 1 / 15 * X234 ^ 3 - 1 / 3 * X234 + 1 / 3 ∧
    u τ 4 = -1 / 10 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 5 = 1 / 15 * X234 ^ 3 ∧
    u τ 6 = 1 / 15 * X234 ^ 3 ∧
    u τ 7 = -1 / 10 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 8 = 1 / 15 * X234 ^ 3 ∧
    u τ 9 = 1 / 15 * X234 ^ 3 ∧
    u τ 10 = -1 / 10 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 11 = 1 / 15 * X234 ^ 3 ∧
    u τ 12 = 1 / 15 * X234 ^ 3 ∧
    u τ 13 = -1 / 10 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 14 = -1 / 10 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 15 = -1 / 10 * X234 ^ 3 + 1 / 6 * X234 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {2, 3, 4}}` of `U5 1`. -/
theorem rootingDist5_1_2 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {2, 3, 4}}) :
    let X01 := exp (-τ.length {0, 1})
    let X234 := exp (-τ.length {2, 3, 4})
    u τ 1 = 1 / 15 * X01 * X234 ^ 3 - 1 / 3 * X01 * X234 + 1 / 3 ∧
    u τ 2 = 1 / 15 * X01 * X234 ^ 3 - 1 / 3 * X01 * X234 + 1 / 3 ∧
    u τ 3 = 1 / 15 * X01 * X234 ^ 3 - 1 / 3 * X01 * X234 + 1 / 3 ∧
    u τ 4 = -1 / 10 * X01 * X234 ^ 3 + 1 / 6 * X01 * X234 ∧
    u τ 5 = 1 / 15 * X01 * X234 ^ 3 ∧
    u τ 6 = 1 / 15 * X01 * X234 ^ 3 ∧
    u τ 7 = -1 / 10 * X01 * X234 ^ 3 + 1 / 6 * X01 * X234 ∧
    u τ 8 = 1 / 15 * X01 * X234 ^ 3 ∧
    u τ 9 = 1 / 15 * X01 * X234 ^ 3 ∧
    u τ 10 = -1 / 10 * X01 * X234 ^ 3 + 1 / 6 * X01 * X234 ∧
    u τ 11 = 1 / 15 * X01 * X234 ^ 3 ∧
    u τ 12 = 1 / 15 * X01 * X234 ^ 3 ∧
    u τ 13 = -1 / 10 * X01 * X234 ^ 3 + 1 / 6 * X01 * X234 ∧
    u τ 14 = -1 / 10 * X01 * X234 ^ 3 + 1 / 6 * X01 * X234 ∧
    u τ 15 = -1 / 10 * X01 * X234 ^ 3 + 1 / 6 * X01 * X234 := by
  sorry

/-- The rooting `hierarchyOf {{2, 3, 4}, {1, 2, 3, 4}}` of `U5 1`. -/
theorem rootingDist5_1_3 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{2, 3, 4}, {1, 2, 3, 4}}) :
    let X234 := exp (-τ.length {2, 3, 4})
    let X1234 := exp (-τ.length {1, 2, 3, 4})
    u τ 1 = 1 / 90 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X234 ^ 3 - 1 / 3 * X234 + 1 / 3 ∧
    u τ 2 = 1 / 90 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X234 ^ 3 - 1 / 3 * X234 + 1 / 3 ∧
    u τ 3 = 1 / 90 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X234 ^ 3 - 1 / 3 * X234 + 1 / 3 ∧
    u τ 4 = 1 / 90 * X234 ^ 3 * X1234 ^ 6 - 1 / 9 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 5 = 1 / 90 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X234 ^ 3 ∧
    u τ 6 = 1 / 90 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X234 ^ 3 ∧
    u τ 7 = 1 / 90 * X234 ^ 3 * X1234 ^ 6 - 1 / 9 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 8 = 1 / 90 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X234 ^ 3 ∧
    u τ 9 = 1 / 90 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X234 ^ 3 ∧
    u τ 10 = 1 / 90 * X234 ^ 3 * X1234 ^ 6 - 1 / 9 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 11 = 1 / 90 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X234 ^ 3 ∧
    u τ 12 = 1 / 90 * X234 ^ 3 * X1234 ^ 6 + 1 / 18 * X234 ^ 3 ∧
    u τ 13 = -2 / 45 * X234 ^ 3 * X1234 ^ 6 - 1 / 18 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 14 = -2 / 45 * X234 ^ 3 * X1234 ^ 6 - 1 / 18 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 15 = -2 / 45 * X234 ^ 3 * X1234 ^ 6 - 1 / 18 * X234 ^ 3 + 1 / 6 * X234 := by
  sorry

/-- The rooting `hierarchyOf {{2, 3, 4}, {0, 2, 3, 4}}` of `U5 1`. -/
theorem rootingDist5_1_4 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{2, 3, 4}, {0, 2, 3, 4}}) :
    let X234 := exp (-τ.length {2, 3, 4})
    let X0234 := exp (-τ.length {0, 2, 3, 4})
    u τ 1 = 1 / 90 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X234 ^ 3 - 1 / 3 * X234 + 1 / 3 ∧
    u τ 2 = 1 / 90 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X234 ^ 3 - 1 / 3 * X234 + 1 / 3 ∧
    u τ 3 = 1 / 90 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X234 ^ 3 - 1 / 3 * X234 + 1 / 3 ∧
    u τ 4 = -2 / 45 * X234 ^ 3 * X0234 ^ 6 - 1 / 18 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 5 = 1 / 90 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X234 ^ 3 ∧
    u τ 6 = 1 / 90 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X234 ^ 3 ∧
    u τ 7 = -2 / 45 * X234 ^ 3 * X0234 ^ 6 - 1 / 18 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 8 = 1 / 90 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X234 ^ 3 ∧
    u τ 9 = 1 / 90 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X234 ^ 3 ∧
    u τ 10 = -2 / 45 * X234 ^ 3 * X0234 ^ 6 - 1 / 18 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 11 = 1 / 90 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X234 ^ 3 ∧
    u τ 12 = 1 / 90 * X234 ^ 3 * X0234 ^ 6 + 1 / 18 * X234 ^ 3 ∧
    u τ 13 = 1 / 90 * X234 ^ 3 * X0234 ^ 6 - 1 / 9 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 14 = 1 / 90 * X234 ^ 3 * X0234 ^ 6 - 1 / 9 * X234 ^ 3 + 1 / 6 * X234 ∧
    u τ 15 = 1 / 90 * X234 ^ 3 * X0234 ^ 6 - 1 / 9 * X234 ^ 3 + 1 / 6 * X234 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {0, 1, 3, 4}}` of `U5 1`. -/
theorem rootingDist5_1_5 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {0, 1, 3, 4}}) :
    let X01 := exp (-τ.length {0, 1})
    let X0134 := exp (-τ.length {0, 1, 3, 4})
    u τ 1 = -2 / 45 * X01 * X0134 ^ 6 - 2 / 9 * X01 + 1 / 3 ∧
    u τ 2 = 1 / 90 * X01 * X0134 ^ 6 - 5 / 18 * X01 + 1 / 3 ∧
    u τ 3 = 1 / 90 * X01 * X0134 ^ 6 - 5 / 18 * X01 + 1 / 3 ∧
    u τ 4 = 1 / 90 * X01 * X0134 ^ 6 + 1 / 18 * X01 ∧
    u τ 5 = 1 / 90 * X01 * X0134 ^ 6 + 1 / 18 * X01 ∧
    u τ 6 = 1 / 90 * X01 * X0134 ^ 6 + 1 / 18 * X01 ∧
    u τ 7 = 1 / 90 * X01 * X0134 ^ 6 + 1 / 18 * X01 ∧
    u τ 8 = -2 / 45 * X01 * X0134 ^ 6 + 1 / 9 * X01 ∧
    u τ 9 = 1 / 90 * X01 * X0134 ^ 6 + 1 / 18 * X01 ∧
    u τ 10 = 1 / 90 * X01 * X0134 ^ 6 + 1 / 18 * X01 ∧
    u τ 11 = -2 / 45 * X01 * X0134 ^ 6 + 1 / 9 * X01 ∧
    u τ 12 = 1 / 90 * X01 * X0134 ^ 6 + 1 / 18 * X01 ∧
    u τ 13 = 1 / 90 * X01 * X0134 ^ 6 + 1 / 18 * X01 ∧
    u τ 14 = 1 / 90 * X01 * X0134 ^ 6 + 1 / 18 * X01 ∧
    u τ 15 = 1 / 90 * X01 * X0134 ^ 6 + 1 / 18 * X01 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {0, 1, 2, 4}}` of `U5 1`. -/
theorem rootingDist5_1_6 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {0, 1, 2, 4}}) :
    let X01 := exp (-τ.length {0, 1})
    let X0124 := exp (-τ.length {0, 1, 2, 4})
    u τ 1 = 1 / 90 * X01 * X0124 ^ 6 - 5 / 18 * X01 + 1 / 3 ∧
    u τ 2 = -2 / 45 * X01 * X0124 ^ 6 - 2 / 9 * X01 + 1 / 3 ∧
    u τ 3 = 1 / 90 * X01 * X0124 ^ 6 - 5 / 18 * X01 + 1 / 3 ∧
    u τ 4 = 1 / 90 * X01 * X0124 ^ 6 + 1 / 18 * X01 ∧
    u τ 5 = -2 / 45 * X01 * X0124 ^ 6 + 1 / 9 * X01 ∧
    u τ 6 = 1 / 90 * X01 * X0124 ^ 6 + 1 / 18 * X01 ∧
    u τ 7 = 1 / 90 * X01 * X0124 ^ 6 + 1 / 18 * X01 ∧
    u τ 8 = 1 / 90 * X01 * X0124 ^ 6 + 1 / 18 * X01 ∧
    u τ 9 = 1 / 90 * X01 * X0124 ^ 6 + 1 / 18 * X01 ∧
    u τ 10 = 1 / 90 * X01 * X0124 ^ 6 + 1 / 18 * X01 ∧
    u τ 11 = 1 / 90 * X01 * X0124 ^ 6 + 1 / 18 * X01 ∧
    u τ 12 = -2 / 45 * X01 * X0124 ^ 6 + 1 / 9 * X01 ∧
    u τ 13 = 1 / 90 * X01 * X0124 ^ 6 + 1 / 18 * X01 ∧
    u τ 14 = 1 / 90 * X01 * X0124 ^ 6 + 1 / 18 * X01 ∧
    u τ 15 = 1 / 90 * X01 * X0124 ^ 6 + 1 / 18 * X01 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1}, {0, 1, 2, 3}}` of `U5 1`. -/
theorem rootingDist5_1_7 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1}, {0, 1, 2, 3}}) :
    let X01 := exp (-τ.length {0, 1})
    let X0123 := exp (-τ.length {0, 1, 2, 3})
    u τ 1 = 1 / 90 * X01 * X0123 ^ 6 - 5 / 18 * X01 + 1 / 3 ∧
    u τ 2 = 1 / 90 * X01 * X0123 ^ 6 - 5 / 18 * X01 + 1 / 3 ∧
    u τ 3 = -2 / 45 * X01 * X0123 ^ 6 - 2 / 9 * X01 + 1 / 3 ∧
    u τ 4 = 1 / 90 * X01 * X0123 ^ 6 + 1 / 18 * X01 ∧
    u τ 5 = 1 / 90 * X01 * X0123 ^ 6 + 1 / 18 * X01 ∧
    u τ 6 = -2 / 45 * X01 * X0123 ^ 6 + 1 / 9 * X01 ∧
    u τ 7 = 1 / 90 * X01 * X0123 ^ 6 + 1 / 18 * X01 ∧
    u τ 8 = 1 / 90 * X01 * X0123 ^ 6 + 1 / 18 * X01 ∧
    u τ 9 = -2 / 45 * X01 * X0123 ^ 6 + 1 / 9 * X01 ∧
    u τ 10 = 1 / 90 * X01 * X0123 ^ 6 + 1 / 18 * X01 ∧
    u τ 11 = 1 / 90 * X01 * X0123 ^ 6 + 1 / 18 * X01 ∧
    u τ 12 = 1 / 90 * X01 * X0123 ^ 6 + 1 / 18 * X01 ∧
    u τ 13 = 1 / 90 * X01 * X0123 ^ 6 + 1 / 18 * X01 ∧
    u τ 14 = 1 / 90 * X01 * X0123 ^ 6 + 1 / 18 * X01 ∧
    u τ 15 = 1 / 90 * X01 * X0123 ^ 6 + 1 / 18 * X01 := by
  sorry

/-- The rooting `hierarchyOf ∅` of `U5 0`. -/
theorem rootingDist5_0_0 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf ∅) :
    u τ 1 = 1 / 15 ∧
    u τ 2 = 1 / 15 ∧
    u τ 3 = 1 / 15 ∧
    u τ 4 = 1 / 15 ∧
    u τ 5 = 1 / 15 ∧
    u τ 6 = 1 / 15 ∧
    u τ 7 = 1 / 15 ∧
    u τ 8 = 1 / 15 ∧
    u τ 9 = 1 / 15 ∧
    u τ 10 = 1 / 15 ∧
    u τ 11 = 1 / 15 ∧
    u τ 12 = 1 / 15 ∧
    u τ 13 = 1 / 15 ∧
    u τ 14 = 1 / 15 ∧
    u τ 15 = 1 / 15 := by
  sorry

/-- The rooting `hierarchyOf {{1, 2, 3, 4}}` of `U5 0`. -/
theorem rootingDist5_0_1 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{1, 2, 3, 4}}) :
    let X1234 := exp (-τ.length {1, 2, 3, 4})
    u τ 1 = 1 / 90 * X1234 ^ 6 + 1 / 18 ∧
    u τ 2 = 1 / 90 * X1234 ^ 6 + 1 / 18 ∧
    u τ 3 = 1 / 90 * X1234 ^ 6 + 1 / 18 ∧
    u τ 4 = 1 / 90 * X1234 ^ 6 + 1 / 18 ∧
    u τ 5 = 1 / 90 * X1234 ^ 6 + 1 / 18 ∧
    u τ 6 = 1 / 90 * X1234 ^ 6 + 1 / 18 ∧
    u τ 7 = 1 / 90 * X1234 ^ 6 + 1 / 18 ∧
    u τ 8 = 1 / 90 * X1234 ^ 6 + 1 / 18 ∧
    u τ 9 = 1 / 90 * X1234 ^ 6 + 1 / 18 ∧
    u τ 10 = 1 / 90 * X1234 ^ 6 + 1 / 18 ∧
    u τ 11 = 1 / 90 * X1234 ^ 6 + 1 / 18 ∧
    u τ 12 = 1 / 90 * X1234 ^ 6 + 1 / 18 ∧
    u τ 13 = -2 / 45 * X1234 ^ 6 + 1 / 9 ∧
    u τ 14 = -2 / 45 * X1234 ^ 6 + 1 / 9 ∧
    u τ 15 = -2 / 45 * X1234 ^ 6 + 1 / 9 := by
  sorry

/-- The rooting `hierarchyOf {{0, 2, 3, 4}}` of `U5 0`. -/
theorem rootingDist5_0_2 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 2, 3, 4}}) :
    let X0234 := exp (-τ.length {0, 2, 3, 4})
    u τ 1 = 1 / 90 * X0234 ^ 6 + 1 / 18 ∧
    u τ 2 = 1 / 90 * X0234 ^ 6 + 1 / 18 ∧
    u τ 3 = 1 / 90 * X0234 ^ 6 + 1 / 18 ∧
    u τ 4 = -2 / 45 * X0234 ^ 6 + 1 / 9 ∧
    u τ 5 = 1 / 90 * X0234 ^ 6 + 1 / 18 ∧
    u τ 6 = 1 / 90 * X0234 ^ 6 + 1 / 18 ∧
    u τ 7 = -2 / 45 * X0234 ^ 6 + 1 / 9 ∧
    u τ 8 = 1 / 90 * X0234 ^ 6 + 1 / 18 ∧
    u τ 9 = 1 / 90 * X0234 ^ 6 + 1 / 18 ∧
    u τ 10 = -2 / 45 * X0234 ^ 6 + 1 / 9 ∧
    u τ 11 = 1 / 90 * X0234 ^ 6 + 1 / 18 ∧
    u τ 12 = 1 / 90 * X0234 ^ 6 + 1 / 18 ∧
    u τ 13 = 1 / 90 * X0234 ^ 6 + 1 / 18 ∧
    u τ 14 = 1 / 90 * X0234 ^ 6 + 1 / 18 ∧
    u τ 15 = 1 / 90 * X0234 ^ 6 + 1 / 18 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1, 3, 4}}` of `U5 0`. -/
theorem rootingDist5_0_3 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1, 3, 4}}) :
    let X0134 := exp (-τ.length {0, 1, 3, 4})
    u τ 1 = -2 / 45 * X0134 ^ 6 + 1 / 9 ∧
    u τ 2 = 1 / 90 * X0134 ^ 6 + 1 / 18 ∧
    u τ 3 = 1 / 90 * X0134 ^ 6 + 1 / 18 ∧
    u τ 4 = 1 / 90 * X0134 ^ 6 + 1 / 18 ∧
    u τ 5 = 1 / 90 * X0134 ^ 6 + 1 / 18 ∧
    u τ 6 = 1 / 90 * X0134 ^ 6 + 1 / 18 ∧
    u τ 7 = 1 / 90 * X0134 ^ 6 + 1 / 18 ∧
    u τ 8 = -2 / 45 * X0134 ^ 6 + 1 / 9 ∧
    u τ 9 = 1 / 90 * X0134 ^ 6 + 1 / 18 ∧
    u τ 10 = 1 / 90 * X0134 ^ 6 + 1 / 18 ∧
    u τ 11 = -2 / 45 * X0134 ^ 6 + 1 / 9 ∧
    u τ 12 = 1 / 90 * X0134 ^ 6 + 1 / 18 ∧
    u τ 13 = 1 / 90 * X0134 ^ 6 + 1 / 18 ∧
    u τ 14 = 1 / 90 * X0134 ^ 6 + 1 / 18 ∧
    u τ 15 = 1 / 90 * X0134 ^ 6 + 1 / 18 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1, 2, 4}}` of `U5 0`. -/
theorem rootingDist5_0_4 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1, 2, 4}}) :
    let X0124 := exp (-τ.length {0, 1, 2, 4})
    u τ 1 = 1 / 90 * X0124 ^ 6 + 1 / 18 ∧
    u τ 2 = -2 / 45 * X0124 ^ 6 + 1 / 9 ∧
    u τ 3 = 1 / 90 * X0124 ^ 6 + 1 / 18 ∧
    u τ 4 = 1 / 90 * X0124 ^ 6 + 1 / 18 ∧
    u τ 5 = -2 / 45 * X0124 ^ 6 + 1 / 9 ∧
    u τ 6 = 1 / 90 * X0124 ^ 6 + 1 / 18 ∧
    u τ 7 = 1 / 90 * X0124 ^ 6 + 1 / 18 ∧
    u τ 8 = 1 / 90 * X0124 ^ 6 + 1 / 18 ∧
    u τ 9 = 1 / 90 * X0124 ^ 6 + 1 / 18 ∧
    u τ 10 = 1 / 90 * X0124 ^ 6 + 1 / 18 ∧
    u τ 11 = 1 / 90 * X0124 ^ 6 + 1 / 18 ∧
    u τ 12 = -2 / 45 * X0124 ^ 6 + 1 / 9 ∧
    u τ 13 = 1 / 90 * X0124 ^ 6 + 1 / 18 ∧
    u τ 14 = 1 / 90 * X0124 ^ 6 + 1 / 18 ∧
    u τ 15 = 1 / 90 * X0124 ^ 6 + 1 / 18 := by
  sorry

/-- The rooting `hierarchyOf {{0, 1, 2, 3}}` of `U5 0`. -/
theorem rootingDist5_0_5 (τ : SpeciesTree (Fin 5)) (hτ : τ.clusters = hierarchyOf {{0, 1, 2, 3}}) :
    let X0123 := exp (-τ.length {0, 1, 2, 3})
    u τ 1 = 1 / 90 * X0123 ^ 6 + 1 / 18 ∧
    u τ 2 = 1 / 90 * X0123 ^ 6 + 1 / 18 ∧
    u τ 3 = -2 / 45 * X0123 ^ 6 + 1 / 9 ∧
    u τ 4 = 1 / 90 * X0123 ^ 6 + 1 / 18 ∧
    u τ 5 = 1 / 90 * X0123 ^ 6 + 1 / 18 ∧
    u τ 6 = -2 / 45 * X0123 ^ 6 + 1 / 9 ∧
    u τ 7 = 1 / 90 * X0123 ^ 6 + 1 / 18 ∧
    u τ 8 = 1 / 90 * X0123 ^ 6 + 1 / 18 ∧
    u τ 9 = -2 / 45 * X0123 ^ 6 + 1 / 9 ∧
    u τ 10 = 1 / 90 * X0123 ^ 6 + 1 / 18 ∧
    u τ 11 = 1 / 90 * X0123 ^ 6 + 1 / 18 ∧
    u τ 12 = 1 / 90 * X0123 ^ 6 + 1 / 18 ∧
    u τ 13 = 1 / 90 * X0123 ^ 6 + 1 / 18 ∧
    u τ 14 = 1 / 90 * X0123 ^ 6 + 1 / 18 ∧
    u τ 15 = 1 / 90 * X0123 ^ 6 + 1 / 18 := by
  sorry

end ADR11
